-- =====================================================================
-- FARM PLAN · 009 · Cargos (descrição do cargo) e Remuneração
-- Base do Contrato de Resultados impresso (modelo da planilha):
--  • cargos: superior imediato, atitudes, experiência e conhecimentos desejáveis…
--  • remuneracao: salário base e % de bonificação por trimestre.
--    Só gestor, administrativo e consultor enxergam (colaborador NÃO vê salário).
-- Traz os dados das abas "Cargos e Funções" e "Equipe" da planilha.
-- Pode rodar mais de uma vez sem problema.
-- =====================================================================
create table if not exists cargos (
  id                    uuid primary key default gen_random_uuid(),
  fazenda_id            uuid not null references fazendas(id) on delete cascade,
  nome                  text not null,
  superior              text,
  funcao_principal      text,
  descricao             text,
  missao                text,
  disponibilidades      text,
  epis                  text,
  formacao              text,
  experiencia           text,
  conhecimentos_obrig   text,
  conhecimentos_desej   text,
  atitudes              text,
  unique (fazenda_id, nome)
);
create table if not exists remuneracao (
  pessoa_id      uuid primary key references pessoas(id) on delete cascade,
  fazenda_id     uuid not null references fazendas(id) on delete cascade,
  salario_base   numeric(12,2),
  bonus_pct      numeric(5,2) not null default 50,   -- % do salário pago por trimestre, conforme a nota
  vinculo        text
);
alter table cargos      enable row level security;
alter table remuneracao enable row level security;
drop policy if exists "ver cargos" on cargos;
drop policy if exists "gerir cargos" on cargos;
drop policy if exists "ver remuneracao" on remuneracao;
drop policy if exists "gerir remuneracao" on remuneracao;
create policy "ver cargos"   on cargos for select using (fazenda_id in (select minhas_fazendas()));
create policy "gerir cargos" on cargos for all using (tenho_papel(fazenda_id, array['consultor','gestor','administrativo']))
                                       with check (tenho_papel(fazenda_id, array['consultor','gestor','administrativo']));
create policy "ver remuneracao"   on remuneracao for select using (tenho_papel(fazenda_id, array['consultor','gestor','administrativo']));
create policy "gerir remuneracao" on remuneracao for all using (tenho_papel(fazenda_id, array['consultor','gestor','administrativo']))
                                            with check (tenho_papel(fazenda_id, array['consultor','gestor','administrativo']));

do $$
declare fz uuid;
begin
  select id into fz from fazendas where nome = 'Fazenda Rio Juruena' limit 1;
  if fz is null then return; end if;

  insert into cargos (fazenda_id, nome, superior, funcao_principal, descricao, missao, disponibilidades, epis, formacao, experiencia, conhecimentos_obrig, conhecimentos_desej, atitudes) values (fz, 'Assistente ADM', 'Diretor', 'Executar atividades administrativas e financeiras, incluindo controle de contas, organização de documentações legais e fiscais, e apoio à gestão de projetos, garantindo o suporte necessário às operações da fazenda de bovinos.', 'Monitorar prazos, metas, investimentos, custos e receitas', 'Executar atividades administrativas e financeiras, incluindo controle de contas, organização de documentações legais e fiscais, e apoio à gestão de projetos, garantindo o suporte necessário às operações da fazenda de bovinos.', 'Flexibilidade para trabalhar em horários variados, incluindo finais de semana e feriados, conforme as necessidades da fazenda. Também é importante ter capacidade de adaptação a mudanças de agenda e disposição para alternar entre trabalho no escritório e campo,', 'Não se aplica', 'Formação exigida: Ensino médio completo (com conhecimentos em rotinas administrativas e financeiras).

Formação desejável: Ensino superior completo ou em curso em Administração, Contabilidade, ou áreas correlatas.', 'Gestão financeira; Controle de estoque e compras; Gestão de documentos; Folha de pagamento e benefícios; Gestão de contratos; Relatórios financeiros; Apoio administrativo', 'Domínio de ferramentas do pacote Office, especialmente Excel.
Conhecimento básico em legislação fiscal e tributária.
Habilidade em elaboração e interpretação de relatórios financeiro', 'Conhecimento em contabilidade e finanças rurais; Legislação trabalhista e fiscal; Gestão de fluxo de caixa; Controle de inventário e logística de insumos; Sistemas de gestão empresarial (ERP); Planejamento de compras e orçamentos; Processos de conformidade e auditoria; Noções de legislação ambiental e de saúde pública; Gestão de recursos humanos e benefícios; Processos administrativos e operacionais da pecuária', 'Organização e atenção aos detalhes.
Proatividade e capacidade de resolver problemas.
Boa comunicação e relacionamento interpessoal.
Adaptabilidade e flexibilidade diante de mudanças e demandas.') on conflict (fazenda_id, nome) do nothing;
  insert into cargos (fazenda_id, nome, superior, funcao_principal, descricao, missao, disponibilidades, epis, formacao, experiencia, conhecimentos_obrig, conhecimentos_desej, atitudes) values (fz, 'Administrativo', 'Diretor', 'Responsável pelo suporte administrativo e operacional em atividades de gestão de documentos, controle financeiro, TI e rastreabilidade, garantindo a organização e execução eficiente dos processos relacionados às operações das fazendas. Atua no acompanhamento de movimentações de rebanho, atualização de sistemas e na comunicação com parceiros e órgãos reguladores, assegurando a conformidade documental e a qualidade das informações.', null, 'Responsável pelo suporte administrativo e operacional em atividades de gestão de documentos, controle financeiro, TI e rastreabilidade, garantindo a organização e execução eficiente dos processos relacionados às operações das fazendas. Atua no acompanhamento de movimentações de rebanho, atualização de sistemas e na comunicação com parceiros e órgãos reguladores, assegurando a conformidade documental e a qualidade das informações.', 'Flexibilidade para trabalhar em horários variados, incluindo finais de semana e feriados, conforme as necessidades da fazenda. Também é importante ter capacidade de adaptação a mudanças de agenda e disposição para alternar entre trabalho no escritório e campo,', 'Não se aplica', 'Formação exigida: Ensino médio completo (com conhecimentos em rotinas administrativas e financeiras).

Formação desejável: Ensino superior completo ou em curso em Administração, Contabilidade, ou áreas correlatas.', 'Experiência com gestão de documentos, resolução de problemas administrativos, atenção aos detalhes, cumprimento de prazos, comunicação clara, adaptação a mudanças, manutenção da confidencialidade, trabalho em equipe, resiliência sob pressão e foco em resultados.', 'Domínio de ferramentas do pacote Office, especialmente Excel.
Conhecimento básico em legislação fiscal e tributária.
Habilidade em elaboração e interpretação de relatórios financeiro', 'Conhecimento em contabilidade e finanças rurais; Legislação trabalhista e fiscal; Gestão de fluxo de caixa; Controle de inventário e logística de insumos; Sistemas de gestão empresarial (ERP); Planejamento de compras e orçamentos; Processos de conformidade e auditoria; Noções de legislação ambiental e de saúde pública; Gestão de recursos humanos e benefícios; Processos administrativos e operacionais da pecuária', 'Organização: Estruturar informações com precisão. Proatividade: Antecipar e resolver problemas; Atenção aos detalhes: Garantir exatidão de dados; Responsabilidade: Cumprir prazos e cronograma; Comunicação clara: Transmitir informações objetivas; Adaptabilidade: Lidar com múltiplas tarefas; Discrição: Manter confidencialidade; Resiliência: Manter produtividade sob pressão; Foco em resultados: Entregar informações precisas.') on conflict (fazenda_id, nome) do nothing;
  insert into cargos (fazenda_id, nome, superior, funcao_principal, descricao, missao, disponibilidades, epis, formacao, experiencia, conhecimentos_obrig, conhecimentos_desej, atitudes) values (fz, 'Gerente Geral', 'Diretor', 'Responsável por gerenciar, executar, monitorar e acompanhar as atividades agropecuárias, garantindo o cumprimento de prazos e metas estabelecidas, corrigindo desvios, solucionando problemas e gerando informações que embasem decisões estratégicas, enquanto promove um ambiente de segurança e liderança para as equipes.', null, 'Responsável por gerenciar, executar, monitorar e acompanhar as atividades agropecuárias, garantindo o cumprimento de prazos e metas estabelecidas, corrigindo desvios, solucionando problemas e gerando informações que embasem decisões estratégicas, enquanto promove um ambiente de segurança e liderança para as equipes.', 'Residir na fazenda', 'Não se aplica', 'Formação exigida: Ensino superior completo em Agronomia, Medicina Veterinária, Zootecnia ou áreas correlatas.

Formação desejável: Especialização ou MBA em Gestão Agropecuária, Gestão de Pessoas ou áreas correlatas.', 'Experiência em gestão agropecuária, manejo de gado em confinamento e recria, liderança de equipes, controle financeiro e orçamentário, logística de insumos e transporte, manutenção de máquinas e infraestrutura. Conhecimento em boas práticas ambientais, normativas sanitárias e segurança do trabalho, além de habilidades estratégicas para otimizar a produção e eficiência operacional.', 'Sólidos conhecimentos em manejo agropecuário, gestão de rebanho e operações rurais. Habilidade na análise de indicadores produtivos e financeiros. Conhecimento em normas de segurança no trabalho e bem-estar animal. Capacidade de gestão estratégica e solução de problemas.', 'Domínio de ferramentas de gestão e sistemas ERP do agronegócio.', 'Liderança e capacidade de inspirar e motivar equipes.
Proatividade e foco em soluções.
Boa comunicação e habilidade de negociação.
Organização e habilidade para trabalhar sob pressão.
Visão estratégica e tomada de decisão embasada.') on conflict (fazenda_id, nome) do nothing;
  insert into cargos (fazenda_id, nome, superior, funcao_principal, descricao, missao, disponibilidades, epis, formacao, experiencia, conhecimentos_obrig, conhecimentos_desej, atitudes) values (fz, 'Controller', 'Gerente Geral', 'Responsável pela gestão do sistema de controle de rebanho, manejo de curral, logística de trato, controle de almoxarifado e suporte às equipes de manejo, garantindo a organização de dados e a elaboração de relatórios mensais para subsidiar a tomada de decisões.', null, 'Responsável pela gestão do sistema de controle de rebanho, manejo de curral, logística de trato, controle de almoxarifado e suporte às equipes de manejo, garantindo a organização de dados e a elaboração de relatórios mensais para subsidiar a tomada de decisões.', 'Residir na fazenda', 'Não se aplica', 'Formação exigida: Ensino médio completo (com conhecimentos técnicos em agropecuária e controle administrativo).

Formação desejável: Ensino superior completo ou em curso em Zootecnia, Veterinária, Agronegócio ou áreas correlatas.', 'Experiência com elaboração de relatórios e controles diários. Facilidade com números e manejo de entrada e saída de animais da fazenda.', 'Conhecimento em softwares de gestão de rebanhos e controle de estoque.
Domínio do pacote Office, com foco em Excel.
Habilidade em organização e análise de relatórios.', 'Conhecimentos em rastreabilidade bovina e softwares de gestão, como TGC.', 'Organização e atenção aos detalhes.
Proatividade e iniciativa na solução de problemas. Boa comunicação e trabalho em equipe. Capacidade de priorizar tarefas e cumprir prazos. Responsabilidade e comprometimento com a qualidade das informações.') on conflict (fazenda_id, nome) do nothing;
  insert into cargos (fazenda_id, nome, superior, funcao_principal, descricao, missao, disponibilidades, epis, formacao, experiencia, conhecimentos_obrig, conhecimentos_desej, atitudes) values (fz, 'Supervisora de Confinamento', 'Gerente Geral', 'Responsável por supervisionar e liderar a equipe do confinamento, garantindo a execução eficiente das atividades relacionadas ao manejo de gado, sanidade animal, processamento de entrada e saída de gado, e rastreabilidade. Atua de forma estratégica no controle de insumos, indicadores nutricionais e zootécnicos, assegurando o desempenho operacional e os resultados da fazenda.', null, 'Supervisionar e liderar a equipe do confinamento, garantindo a execução eficiente do manejo de gado, sanidade, entrada e saída de animais e rastreabilidade. Controlar insumos, indicadores nutricionais e zootécnicos, assegurando sempre a melhoria do desempenho e resultados da fazenda.', 'Residir em alojamento na fazenda', null, 'Formação exigida: Graduação em Zootecnia, Medicina Veterinária ou áreas correlatas.

Formação desejável: Pós-graduação em Produção Animal, Gestão Agropecuária ou áreas relacionadas.', 'Experiência em monitoramento e análise de indicadores nutricionais, sanitários e zootécnicos, ajustando estratégias para melhorar o desempenho do gado. Habilidade em liderar e capacitar equipes, além de elaborar relatórios operacionais e manter informações atualizadas no TGC.', 'Conhecimento em manejo de confinamento, nutrição e sanidade animal.
Experiência em controle de insumos e estoque. Habilidade em análise e gestão de indicadores zootécnicos e nutricionais. Conhecimento em manutenção de equipamentos agrícolas. Familiaridade com ferramentas e softwares de gestão agropecuária. Domínio de normas de rastreabilidade e bem-estar animal.', 'Conhecimentos em manejo de gado, cuidados sanitários, bem-estar animal, gestão de equipes, operações de confinamento, manutenção preventiva de equipamentos, segurança no trabalho e habilidades de planejamento e organização', 'Liderança e habilidade para gerir motivar e capacitar equipes, de maneira eficaz promovendo um ambiente de trabalho colaborativo e focado em resultados. 
Organização e atenção aos detalhes.
Proatividade e visão estratégica para solucionar problemas e melhorar processos.
Comunicação clara e assertiva.
Capacidade de trabalhar sob pressão e manter o foco em metas e resultados.') on conflict (fazenda_id, nome) do nothing;
  insert into cargos (fazenda_id, nome, superior, funcao_principal, descricao, missao, disponibilidades, epis, formacao, experiencia, conhecimentos_obrig, conhecimentos_desej, atitudes) values (fz, 'Líder de Gado', 'Gerente Geral', 'Liderar e supervisionar o time de vaqueiros da fazenda, distribuindo tarefas e acompanhando a execução das atividades. 
Participar da gestão completa do rebanho, incluindo: monitoramento do pesagens,  do desempenho dos animais, etc. Responsável pela chegada e embarque dos animais na fazenda (contagem, avaliação e execução de protocolo nutricional e sanitário). Identificação e apontamento de problemas relacionados à saúde, manejo ou infraestrutura. Gerenciamento do rodeio do gado. Responsável pela contagem do gado, no pasto e no confinamento. Responsável pela execução das atividades inerentes a pastagens: controle de plantas daninhas, manejo de pragas e doenças, adubação, controle de entrada e saída de animais, execução de ajustes de taxas de lotação.
Planejar e executar ações preventivas e corretivas para atender às necessidades do rebanho e manter a eficiência produtiva. Monitorar a saúde do rebanho, identificando sinais de doenças ou lesões, e realizar tratamentos preventivos e curativos conforme orientações.
Participar das atividades de recria e engorda dos animais, assegurando o cumprimento dos protocolos de nutrição e manejo.
Garantir o cumprimento das normas de bem-estar animal e segurança no trabalho durante as operações de manejo.
Trabalhar em parceria com os setores administrativo, máquinas e confinamento,  alinhando as necessidades do manejo com a disponibilidade de recursos. Garantir e zelar pelo cuidado e manutenções preventivas  dos equipamentos de trabalho. Ligar e desligar geradores quando necessário.
Participar do processo de avaliação de novos contratados da equipe de vaqueiros. Treinar e capacitar a equipe de vaqueiros.
Liderar e engajar a equipe de vaqueiros para atingir as metas e obter os resultados esperados da fazenda.', null, 'Responsável por liderar a equipe de peões da fazenda, realizar a gestão completa do gado e monitorar os principais índices produtivos da propriedade, garantindo a eficiência nas operações de reprodução, manejo e bem-estar animal.', 'Residir na fazenda e liderar a equipe de vaqueiros e auxiliares de manejo.', null, 'Formação exigida: Ensino fundamental completo (com experiência comprovada em manejo de gado).

Formação desejável: Ensino técnico ou superior em Zootecnia, Veterinária, Agronegócio ou áreas correlatas.', 'Experiência com liderança de equipes de vaqueiros, manejo de rebanho (monitoramento de saúde, pesagens e desempenho), garantindo bem-estar animal.', 'Conhecimento avançado em manejo de gado de corte,  sanidade animal.
Habilidade no uso de ferramentas para registro e controle de dados zootécnicos.
Noções de nutrição animal e manejo de pastagens.
Conhecimento em técnicas de liderança e gestão de equipes.', 'Liderança e capacidade de motivar equipes.
Organização e atenção aos detalhes.
Proatividade na identificação e resolução de problemas.
Boa comunicação e habilidade de negociação.
Comprometimento com os resultados e objetivos da fazenda.', 'Supervisionar e liderar os vaqueiros, distribuindo tarefas e acompanhando a execução das atividades. Auxiliar na gestão do rebanho, monitorando pesagens e desempenho dos animais. Identificar e relatar problemas de saúde, manejo ou infraestrutura. Planejar e executar ações preventivas e corretivas para atender às necessidades do rebanho e manter a eficiência produtiva. Participar das atividades de recria e engorda dos animais, assegurando o cumprimento dos protocolos de nutrição e manejo. Assegurar o bem-estar animal e a segurança no trabalho no manejo. Garantir a manutenção preventiva e o cuidado com os equipamentos de trabalho e colaborar na avaliação de novos vaqueiros.') on conflict (fazenda_id, nome) do nothing;
  insert into cargos (fazenda_id, nome, superior, funcao_principal, descricao, missao, disponibilidades, epis, formacao, experiencia, conhecimentos_obrig, conhecimentos_desej, atitudes) values (fz, 'Trabalhador Agropecuário Geral - Vaqueiro', 'Líder de Gado', 'Responsável por realizar o manejo diário do gado, garantindo a contagem, conferência e cuidados com a saúde e bem-estar dos animais. Auxilia na recria e engorda, realiza práticas de sanidade e alimentação, além de contribuir para a manutenção das instalações da fazenda.', null, 'Responsável por realizar o manejo diário do gado, garantindo a contagem, conferência e cuidados com a saúde e bem-estar dos animais. Auxilia na recria e engorda, realiza práticas de sanidade e alimentação, além de contribuir para a manutenção das instalações da fazenda.', 'Residir em alojamento na fazenda', 'Botas de segurança, roupas adequadas, chapéu ou boné.', 'Formação exigida: Ensino fundamental incompleto.

Formação desejável: Conhecimento básico em manejo e bem-estar animal.', 'Experiência com manejo de gado e identificação de problemas de saúde animal.
Experiência em manutenção de cercas, currais e outras estruturas.
Noções de práticas de bem-estar animal e segurança no trabalho rural.', 'Conhecimento básico de práticas de sanidade e alimentação animal. Práticas de segurança ao lidar com animais grandes e pesados. Habilidade para guiar e mover o rebanho de maneira segura e eficiente.', 'Conhecimento de Equipamentos e Ferramentas: Uso adequado de arreios, cordas e outros equipamentos de manejo de gado, como aplicador de vacinas e realizar tratamentos básicos', 'Organização e atenção aos detalhes.
Proatividade e disposição para resolver problemas. Resiliência e capacidade de trabalhar em ambientes externos. Comprometimento com o cuidado dos animais e das instalações. Trabalho em equipe e boa comunicação.') on conflict (fazenda_id, nome) do nothing;
  insert into cargos (fazenda_id, nome, superior, funcao_principal, descricao, missao, disponibilidades, epis, formacao, experiencia, conhecimentos_obrig, conhecimentos_desej, atitudes) values (fz, 'Trabalhador da Pecuária - Vaqueiro', 'Líder de Gado', 'Responsável por realizar o manejo diário do gado, garantindo a contagem, conferência e cuidados com a saúde e bem-estar dos animais. Auxilia na recria e engorda, realiza práticas de sanidade e alimentação, além de contribuir para a manutenção das instalações da fazenda.', null, 'Responsável por realizar o manejo diário do gado, garantindo a contagem, conferência e cuidados com a saúde e bem-estar dos animais. Auxilia na recria e engorda, realiza práticas de sanidade e alimentação, além de contribuir para a manutenção das instalações da fazenda.', 'Residir em alojamento na fazenda', 'Botas de segurança, roupas adequadas, chapéu ou boné.', 'Formação exigida: Ensino fundamental incompleto.

Formação desejável: Conhecimento básico em manejo e bem-estar animal.', 'Experiência com manejo de gado e identificação de problemas de saúde animal.
Experiência em manutenção de cercas, currais e outras estruturas.
Noções de práticas de bem-estar animal e segurança no trabalho rural.', 'Conhecimento básico de práticas de sanidade e alimentação animal. Práticas de segurança ao lidar com animais grandes e pesados. Habilidade para guiar e mover o rebanho de maneira segura e eficiente.', 'Conhecimento de Equipamentos e Ferramentas: Uso adequado de arreios, cordas e outros equipamentos de manejo de gado, como aplicador de vacinas e realizar tratamentos básicos', 'Organização e atenção aos detalhes.
Proatividade e disposição para resolver problemas. Resiliência e capacidade de trabalhar em ambientes externos. Comprometimento com o cuidado dos animais e das instalações. Trabalho em equipe e boa comunicação.') on conflict (fazenda_id, nome) do nothing;
  insert into cargos (fazenda_id, nome, superior, funcao_principal, descricao, missao, disponibilidades, epis, formacao, experiencia, conhecimentos_obrig, conhecimentos_desej, atitudes) values (fz, 'Trabalhador Agropecuário Geral II', 'Coordenador Serviço Geral', 'Responsável por monitorar e realizar manutenção na rede hidráulica da fazenda, garantindo a qualidade e o fornecimento contínuo de água para os animais, além de manter a limpeza de cochos, reservatórios e sistemas de bombeamento.', 'Monitorar e controlar informações financeiras e contábeis do Projeto. Manter dividendos e recebiveis em dias, e documentações em ordem, evitando prejuízos financeiros. Organizar documentos e efetuar sua classificação
contábil. Gerar lançamentos contábeis. auxiliar na apuração dos impostos, conciliar contas e preenchimento de guias de recolhimento e de solicitações. Emitir notas de venda e de transferência; realizam o arquivo de documentos.', 'Responsável por monitorar e realizar manutenção na rede hidráulica da fazenda, garantindo a qualidade e o fornecimento contínuo de água para os animais, além de manter a limpeza de cochos, reservatórios e sistemas de bombeamento.', 'Residir na fazenda', 'Botas de segurança, luvas de proteção, óculos de proteção, chapéu ou boné.', 'Formação exigida: Ensino fundamental completo.

Formação desejável: Curso básico em hidráulica ou manutenção predial.', 'Experiência com limpeza e higienização de bebedouros de confinamento.', 'Conhecimento básico em sistemas hidráulicos e manutenção de redes de abastecimento. Habilidade no uso de ferramentas manuais e equipamentos para reparos hidráulicos. Noções de limpeza e higienização de sistemas de água.', 'Capacidade de monitorar e controlar sistemas de bombeamento e reservatórios. Habilidade para uso de ferramentas manuais como foices, roçadeiras e enxadas.', 'Organização e atenção aos detalhes.
Proatividade e agilidade na resolução de problemas. Comprometimento com a qualidade e segurança do trabalho. Boa comunicação e trabalho em equipe. Responsabilidade e zelo pelos recursos da fazenda.') on conflict (fazenda_id, nome) do nothing;
  insert into cargos (fazenda_id, nome, superior, funcao_principal, descricao, missao, disponibilidades, epis, formacao, experiencia, conhecimentos_obrig, conhecimentos_desej, atitudes) values (fz, 'Trabalhador Agropecuário Geral III', 'Coordenador de máquinas', 'Responsável por fornecer suplementos ao rebanho, realizar o transporte de suplementos entre fábrica e fazenda, monitorar estoques e realizar manutenções preventivas dos equipamentos utilizados, assegurando o suporte necessário às operações diárias.', null, 'Responsável por fornecer suplementos ao rebanho, realizar o transporte de suplementos entre fábrica e fazenda, monitorar estoques e realizar manutenções preventivas dos equipamentos utilizados, assegurando o suporte necessário às operações diárias.', 'Residir na fazenda', 'Botas de segurança', 'Formação exigida: Ensino fundamental completo.

Formação desejável: Curso básico de operação de máquinas agrícolas ou veículos pesados.', 'Habilidade na operação de trator e vagões de trato.
Capacidade de registrar e monitorar dados operacionais.', 'Conhecimento básico de manutenção preventiva de máquinas, veículos e equipamentos.', 'Noções de segurança no trabalho e trânsito', 'Organização e atenção aos detalhes.
Proatividade e responsabilidade na execução das tarefas.
Trabalho em equipe e boa comunicação.
Comprometimento com a segurança e eficiência nas operações.') on conflict (fazenda_id, nome) do nothing;
  insert into cargos (fazenda_id, nome, superior, funcao_principal, descricao, missao, disponibilidades, epis, formacao, experiencia, conhecimentos_obrig, conhecimentos_desej, atitudes) values (fz, 'Trabalhador Agropecuário Geral', 'Supervisora de Confinamento', 'Responsável por executar atividades de limpeza, organização e conservação dos ambientes do confinamento, utilizando materiais e equipamentos adequados, e assegurando o cumprimento das normas de higiene e segurança para manter os espaços funcionais e limpos.', null, 'Responsável por executar atividades de limpeza, organização e conservação dos ambientes do confinamento, utilizando materiais e equipamentos adequados, e assegurando o cumprimento das normas de higiene e segurança para manter os espaços funcionais e limpos.', 'Residir na fazenda', 'Óculos de proteção; Protetores auriculares; Máscara ou respirador (quando necessário)', 'Formação exigida: Ensino fundamental completo.                                
Formação desejável: Conhecimentos básicos sobre segurança no trabalho e uso de produtos de limpeza são desejáveis.', 'Experiência em gestão de estoque, limpeza, operação de pá carregadeira, controle de alimentos e aplicação do sistema 5S. Habilidade em manuseio de lonas, controle de produtos de limpeza, seguimento de normas de segurança, uso de EPIs e apoio em atividades diversas na fazenda.', 'Gestão de Armazenagem; Limpeza e Organização; Operação de Equipamentos; Segurança e Higiene; Controle de Estoque de Insumos; Cuidado com Alimentos e Cobertura; Comunicação e Identificação de Problemas', 'Manuseio de lonas e coberturas de armazenamento; Controle de produtos de limpeza; Identificação e reporte de necessidades de manutenção', 'Organização e atenção aos detalhes.
Proatividade e agilidade na execução das atividades. Comprometimento com a qualidade e segurança. Trabalho em equipe e boa comunicação. Zelo pelo ambiente e equipamentos da fazenda.') on conflict (fazenda_id, nome) do nothing;
  insert into cargos (fazenda_id, nome, superior, funcao_principal, descricao, missao, disponibilidades, epis, formacao, experiencia, conhecimentos_obrig, conhecimentos_desej, atitudes) values (fz, 'Líder de Máquinas', 'Gerente Geral', 'Responsável por gerenciar a manutenção preventiva e corretiva de máquinas e equipamentos agrícolas, supervisionar a conservação de estruturas físicas da fazenda e otimizar a utilização dos recursos disponíveis, garantindo segurança, eficiência e redução de custos operacionais.', null, 'Responsável por gerenciar a manutenção preventiva e corretiva de máquinas e equipamentos agrícolas, supervisionar a conservação de estruturas físicas da fazenda e otimizar a utilização dos recursos disponíveis, garantindo segurança, eficiência e redução de custos operacionais.', 'Residir na fazenda', 'Botas de proteção; Óculos de proteção; Protetores auriculares; Máscara ou respirador (quando necessário)', 'Formação exigida: Ensino médio técnico completo em agropecuária ou mecânica e afins.

Formação desejável: Ensino superior em Engenharia Mecânica, Engenharia Agrícola, ou áreas correlatas.', 'Experiência em manutenção preventiva e corretiva de máquinas agrícolas, diagnóstico e reparo de falhas mecânicas, elétricas e hidráulicas, gestão de equipe, controle de estoque de peças, planejamento de cronogramas de manutenção, interpretação de manuais técnicos, cumprimento de normas de segurança e relacionamento com fornecedores.', 'Conhecimento avançado em manutenção de máquinas e equipamentos agrícolas.
Noções de operação e conservação de estruturas físicas em propriedades rurais.
Habilidade no uso de ferramentas de controle logístico e de manutenção.', 'Conhecimento em segurança do trabalho e gestão de riscos operacionais. Capacidade de planejar e interpretar indicadores de desempenho (KPIs).', 'Liderança e habilidade para gerir equipes técnicas.
Organização e planejamento estratégico.
Proatividade na solução de problemas e busca por inovações.
Boa comunicação e capacidade de trabalhar sob pressão.
Foco em resultados e comprometimento com as metas da fazenda.') on conflict (fazenda_id, nome) do nothing;
  insert into cargos (fazenda_id, nome, superior, funcao_principal, descricao, missao, disponibilidades, epis, formacao, experiencia, conhecimentos_obrig, conhecimentos_desej, atitudes) values (fz, 'Operador de Máquinas I', 'Coordenador de Máquinas', 'Responsável por operar máquinas e implementos agrícolas, realizar manutenção preventiva, e auxiliar em atividades como aplicação de corretivos e adubos, manutenção de estradas e aterros, além de suporte no trato do rebanho, garantindo o bom uso e conservação dos equipamentos.', null, 'Operar pá carregadeira e implementos agrícolas, realizando movimentação de materiais, aplicação de corretivos e adubos. Executar manutenção preventiva e inspeções nas máquinas, além de manter as infraestruturas internas da fazenda, como estradas e aterros. Apoiar o manejo do rebanho e a suplementação alimentar.', 'Seguir normas de segurança no trabalho e comunicar problemas nos equipamentos ao superior. Auxiliar em outras tarefas operacionais conforme orientação.', null, 'Formação exigida: Ensino fundamental completo.

Formação desejável: Curso de operação de máquinas pesadas ou agrícolas.', 'Experiência na operação de pá carregadeira e outros implementos agrícolas. Noções de aplicação de corretivos e adubos. Habilidade para executar trabalhos de infraestrutura, como manutenção de estradas e aterros.', 'Conhecimento básico em manutenção preventiva de máquinas.', 'Conhecimento das normas de segurança no trabalho.', 'Responsabilidade e comprometimento com o bom uso dos equipamentos. Organização e atenção aos detalhes. Proatividade na identificação de problemas e busca de soluções. Trabalho em equipe e boa comunicação. Adaptabilidade para realizar diferentes tarefas dentro da rotina da fazenda.') on conflict (fazenda_id, nome) do nothing;
  insert into cargos (fazenda_id, nome, superior, funcao_principal, descricao, missao, disponibilidades, epis, formacao, experiencia, conhecimentos_obrig, conhecimentos_desej, atitudes) values (fz, 'Trabalhador Pecuário I - Operador Pasto', 'Supervisora de Confinamento', 'Responsável pelo fornecimento de suplementos no pasto e ração no confinamento, transporte de insumos, manutenção preventiva de equipamentos e controle do monitoramento de estoques e fornecimento de alimentos ao gado, assegurando a eficiência e qualidade no manejo alimentar.', null, 'Responsável pelo fornecimento de suplementos no pasto e ração no confinamento, transporte de insumos, manutenção preventiva de equipamentos e controle do monitoramento de estoques e fornecimento de alimentos ao gado, assegurando a eficiência e qualidade no manejo alimentar.', 'Seguir normas de segurança no trabalho e comunicar problemas nos equipamentos ao superior. Auxiliar em outras tarefas operacionais conforme orientação.', 'Botinas de segurança', 'Formação exigida: Ensino fundamental completo.

Formação desejável: Curso básico de operação de veículos agrícolas e conhecimentos em manejo de gado.', 'Habilidade na operação de caminhões e vagões de trato. Conhecimento básico de manutenção preventiva de veículos e implementos agrícolas. Capacidade de registro e monitoramento de dados relacionados à alimentação e manejo do rebanho. Noções de segurança no trabalho e bem-estar animal.', 'Conhecimento básico em manutenção preventiva de máquinas.', 'Conhecimento das normas de segurança no trabalho.', 'Organização e atenção aos detalhes.
Proatividade e agilidade na execução das atividades. Comprometimento com a qualidade do trabalho e o bem-estar dos animais. Boa comunicação e habilidade para trabalho em equipe. Responsabilidade na utilização e conservação dos equipamentos e recursos.') on conflict (fazenda_id, nome) do nothing;
  insert into cargos (fazenda_id, nome, superior, funcao_principal, descricao, missao, disponibilidades, epis, formacao, experiencia, conhecimentos_obrig, conhecimentos_desej, atitudes) values (fz, 'Cozinheira', 'Controller', 'Responsável pelo preparo das refeições na cantina, garantindo a qualidade, higiene e variedade dos alimentos servidos aos colaboradores da fazenda. Limpeza dos escritorio, alojamentos e cantina.', null, 'Responsável pelo preparo das refeições na cantina, garantindo a qualidade, higiene e variedade dos alimentos servidos aos colaboradores da fazenda. E realizar o controle do consumo de carnes e refeições.', 'Residir na fazenda', 'Avental, touca ou rede para cabelo e luvas de proteção (quando necessário)', 'Formação exigida: Ensino fundamental completo.

Formação desejável: Curso básico de culinária ou manipulação de alimentos.', 'Vivência em fazenda, experiência em cozinhar cardápios variados adaptados a necessidade da fazenda e ao número de pessoas.', 'Conhecimento em preparo de refeições e técnicas culinárias. Noções de higiene e segurança alimentar. Habilidade no controle de porções e planejamento de refeições para grupos. Noções básicas sobre limpeza, higienização e organização de ambientes de trabalho.', 'Organização de cozinha e controle de estoque de alimentos e utensílios.', 'Organização e atenção aos detalhes.
Agilidade e pontualidade no preparo e entrega das refeições. Proatividade e adaptabilidade para lidar com demandas variadas. Boa comunicação e habilidade para trabalhar em equipe. Comprometimento com a qualidade do serviço prestado.') on conflict (fazenda_id, nome) do nothing;
  insert into cargos (fazenda_id, nome, superior, funcao_principal, descricao, missao, disponibilidades, epis, formacao, experiencia, conhecimentos_obrig, conhecimentos_desej, atitudes) values (fz, 'Diretor', null, null, null, null, null, null, null, null, null, null, null) on conflict (fazenda_id, nome) do nothing;
  insert into cargos (fazenda_id, nome, superior, funcao_principal, descricao, missao, disponibilidades, epis, formacao, experiencia, conhecimentos_obrig, conhecimentos_desej, atitudes) values (fz, 'Trabalhador Agropecuário I (Limpeza)', 'Líder Serviços Gerais', 'Auxiliar na manutenção estrutural da fazenda, operar máquinas agrícolas simples para limpeza de pastagens, apoiar o manejo de gado no curral e realizar atividades de limpeza e conservação de cochos e bebedouros.', null, 'Auxiliar na manutenção estrutural da fazenda, operar máquinas agrícolas simples para limpeza de pastagens, apoiar o manejo de gado no curral e realizar atividades de limpeza e conservação de cochos e bebedouros.', 'Residir na fazenda', 'Capacete com viseira ou óculos, protetor auricular, luvas, botas de segurança, roupas de proteção (camisa longa e calças), máscara contra poeira e cinto de segurança (se necessário).', 'Formação exigida: Ensino fundamental completo.

Formação desejável: Curso básico em hidráulica ou manutenção predial.', 'Experência com o básico de operação de máquinas agrícolas e manutenção rural.', 'Manejo básico de gado no curral, higiene de cochos e bebedouros, normas de segurança no trabalho, manutenção básica de infraestrutura e cuidados com o bem-estar animal.', 'Normas sanitárias.', 'Proatividade e disposição para aprender.Atenção aos detalhes e zelo pelo ambiente de trabalho. Capacidade de trabalho em equipe. Responsabilidade e comprometimento com as tarefas.') on conflict (fazenda_id, nome) do nothing;
  insert into cargos (fazenda_id, nome, superior, funcao_principal, descricao, missao, disponibilidades, epis, formacao, experiencia, conhecimentos_obrig, conhecimentos_desej, atitudes) values (fz, 'Líder Serviços Gerais', 'Gerente Geral', 'Responsável por supervisionar equipes de serviços gerais, organizar rotinas de trabalho e assegurar a qualidade das atividades de manutenção, limpeza e outros serviços operacionais, com foco na eficiência, segurança e controle de recursos.', null, 'Responsável por supervisionar equipes de serviços gerais, organizar rotinas de trabalho e assegurar a qualidade das atividades de manutenção, limpeza e outros serviços operacionais, com foco na eficiência, segurança e controle de recursos.', 'Residir na fazenda', null, null, null, null, null, null) on conflict (fazenda_id, nome) do nothing;
  insert into remuneracao (pessoa_id, fazenda_id, salario_base, vinculo) select id, fz, 5000, 'Carteira Assinada' from pessoas where fazenda_id = fz and lower(regexp_replace(trim(nome), '\s+', ' ', 'g')) = lower(regexp_replace(trim('Agnaldo Barros da Silva'), '\s+', ' ', 'g')) on conflict (pessoa_id) do nothing;
  insert into remuneracao (pessoa_id, fazenda_id, salario_base, vinculo) select id, fz, 4000, 'Carteira Assinada' from pessoas where fazenda_id = fz and lower(regexp_replace(trim(nome), '\s+', ' ', 'g')) = lower(regexp_replace(trim('Alessandro de Oliveira'), '\s+', ' ', 'g')) on conflict (pessoa_id) do nothing;
  insert into remuneracao (pessoa_id, fazenda_id, salario_base, vinculo) select id, fz, 3000, 'Carteira Assinada' from pessoas where fazenda_id = fz and lower(regexp_replace(trim(nome), '\s+', ' ', 'g')) = lower(regexp_replace(trim('Daniel da Silva Liberato'), '\s+', ' ', 'g')) on conflict (pessoa_id) do nothing;
  insert into remuneracao (pessoa_id, fazenda_id, salario_base, vinculo) select id, fz, 2800, 'Carteira Assinada' from pessoas where fazenda_id = fz and lower(regexp_replace(trim(nome), '\s+', ' ', 'g')) = lower(regexp_replace(trim('Dircilei Jumes Martendal'), '\s+', ' ', 'g')) on conflict (pessoa_id) do nothing;
  insert into remuneracao (pessoa_id, fazenda_id, salario_base, vinculo) select id, fz, 3000, 'Carteira Assinada' from pessoas where fazenda_id = fz and lower(regexp_replace(trim(nome), '\s+', ' ', 'g')) = lower(regexp_replace(trim('Edivaldo Ferreira Cesareto da Silva'), '\s+', ' ', 'g')) on conflict (pessoa_id) do nothing;
  insert into remuneracao (pessoa_id, fazenda_id, salario_base, vinculo) select id, fz, 4000, 'Carteira Assinada' from pessoas where fazenda_id = fz and lower(regexp_replace(trim(nome), '\s+', ' ', 'g')) = lower(regexp_replace(trim('Jhony Max Carvalho dos Santos'), '\s+', ' ', 'g')) on conflict (pessoa_id) do nothing;
  insert into remuneracao (pessoa_id, fazenda_id, salario_base, vinculo) select id, fz, 3000, 'Carteira Assinada' from pessoas where fazenda_id = fz and lower(regexp_replace(trim(nome), '\s+', ' ', 'g')) = lower(regexp_replace(trim('José Maurício da Silva Liberato'), '\s+', ' ', 'g')) on conflict (pessoa_id) do nothing;
  insert into remuneracao (pessoa_id, fazenda_id, salario_base, vinculo) select id, fz, 2000, 'Carteira Assinada' from pessoas where fazenda_id = fz and lower(regexp_replace(trim(nome), '\s+', ' ', 'g')) = lower(regexp_replace(trim('Maria Helena da Silva de Oliveira'), '\s+', ' ', 'g')) on conflict (pessoa_id) do nothing;
  insert into remuneracao (pessoa_id, fazenda_id, salario_base, vinculo) select id, fz, 3600, 'Carteira Assinada' from pessoas where fazenda_id = fz and lower(regexp_replace(trim(nome), '\s+', ' ', 'g')) = lower(regexp_replace(trim('Mariany Carvalho Botelho'), '\s+', ' ', 'g')) on conflict (pessoa_id) do nothing;
  insert into remuneracao (pessoa_id, fazenda_id, salario_base, vinculo) select id, fz, 3000, 'Carteira Assinada' from pessoas where fazenda_id = fz and lower(regexp_replace(trim(nome), '\s+', ' ', 'g')) = lower(regexp_replace(trim('Maicon Douglas  Zerbielli de Oliveira'), '\s+', ' ', 'g')) on conflict (pessoa_id) do nothing;
  insert into remuneracao (pessoa_id, fazenda_id, salario_base, vinculo) select id, fz, null, 'Carteira Assinada' from pessoas where fazenda_id = fz and lower(regexp_replace(trim(nome), '\s+', ' ', 'g')) = lower(regexp_replace(trim('Odirlei José Martendal'), '\s+', ' ', 'g')) on conflict (pessoa_id) do nothing;
  insert into remuneracao (pessoa_id, fazenda_id, salario_base, vinculo) select id, fz, 2400, 'Carteira Assinada' from pessoas where fazenda_id = fz and lower(regexp_replace(trim(nome), '\s+', ' ', 'g')) = lower(regexp_replace(trim('Pedro Antonio Jumes Martendal'), '\s+', ' ', 'g')) on conflict (pessoa_id) do nothing;
  insert into remuneracao (pessoa_id, fazenda_id, salario_base, vinculo) select id, fz, 2800, 'Carteira Assinada' from pessoas where fazenda_id = fz and lower(regexp_replace(trim(nome), '\s+', ' ', 'g')) = lower(regexp_replace(trim('Pedro Lopes dos Santos'), '\s+', ' ', 'g')) on conflict (pessoa_id) do nothing;
  insert into remuneracao (pessoa_id, fazenda_id, salario_base, vinculo) select id, fz, null, 'Carteira Assinada' from pessoas where fazenda_id = fz and lower(regexp_replace(trim(nome), '\s+', ' ', 'g')) = lower(regexp_replace(trim('Vanessa Matilde da Silva'), '\s+', ' ', 'g')) on conflict (pessoa_id) do nothing;
  insert into remuneracao (pessoa_id, fazenda_id, salario_base, vinculo) select id, fz, 3000, 'Carteira Assinada' from pessoas where fazenda_id = fz and lower(regexp_replace(trim(nome), '\s+', ' ', 'g')) = lower(regexp_replace(trim('Jhennifer Rayssa da Silva'), '\s+', ' ', 'g')) on conflict (pessoa_id) do nothing;
  insert into remuneracao (pessoa_id, fazenda_id, salario_base, vinculo) select id, fz, 3000, 'Carteira Assinada' from pessoas where fazenda_id = fz and lower(regexp_replace(trim(nome), '\s+', ' ', 'g')) = lower(regexp_replace(trim('Evilazio Martins Pereira'), '\s+', ' ', 'g')) on conflict (pessoa_id) do nothing;
  insert into remuneracao (pessoa_id, fazenda_id, salario_base, vinculo) select id, fz, 2800, 'Carteira Assinada' from pessoas where fazenda_id = fz and lower(regexp_replace(trim(nome), '\s+', ' ', 'g')) = lower(regexp_replace(trim('Genilson Ferreira Cesareto'), '\s+', ' ', 'g')) on conflict (pessoa_id) do nothing;
end $$;

-- Confere: cada pessoa com cargo cadastrado e salário
select p.apelido, p.cargo, (c.id is not null) as cargo_tem_descricao, r.salario_base
from pessoas p
left join cargos c on c.fazenda_id = p.fazenda_id and lower(trim(c.nome)) = lower(trim(p.cargo))
left join remuneracao r on r.pessoa_id = p.id
order by p.apelido;