-- =====================================================================
-- FARM PLAN · Gesta'Up · 032 · Biblioteca com 5M Pronto
-- Coloca o 5M (Metodologia, Máquinas, Materiais, Meta), a meta em número,
-- o tempo previsto e a Lista de Conferência de 40 atividades comuns
-- na Biblioteca da consultoria.
--  · Atividade que já está na Biblioteca SEM 5M: recebe o 5M.
--  · Atividade que já tem 5M na Biblioteca: NÃO é alterada.
--  · Atividade que não existe: é criada.
-- Não mexe nas fazendas. Nelas, use Cadastros › 5M das Atividades ›
-- 📚 Puxar o 5M da Biblioteca.
-- Pode rodar mais de uma vez sem problema.
-- Rodar: Supabase › SQL Editor › New query › colar › Run.
-- =====================================================================
insert into biblioteca (conta_id, nome, setor_nome, tipo, urgencia, dias, como_fazer, origem)
select c.id, m.nome, m.setor, m.tipo, m.urg, m.dias, m.cf, 'Biblioteca Gesta''Up'
from contas c
cross join (values
  ('Leitura de cocho', 'Gado', '1 - Rotina', 3, '{true,true,true,true,true,true,true}'::boolean[], '{"m2": "1. Passar em todos os cochos sempre no mesmo horário, antes do trato\n2. Dar a nota do cocho: 0 vazio e lambido, 1 pouca sobra, 2 sobra média, 3 muita sobra\n3. Anotar a nota de cada lote no app ou na planilha\n4. Avisar o tratador quanto aumentar ou diminuir em cada lote\n5. Ver se tem água no cocho, sujeira ou ração molhada", "m3": "Moto ou cavalo", "m4": "Planilha ou celular com o app", "m5": "Todos os lotes lidos antes do trato da manhã", "meta_qtd": 1, "meta_unid": "Leitura por Lote", "tempo_h": 1, "checklist": []}'::jsonb),
  ('Bebedouros - Limpeza', 'Gado', '1 - Rotina', 1, '{true,false,true,false,true,false,false}'::boolean[], '{"m2": "1. Fechar o registro\n2. Esvaziar o bebedouro\n3. Retirar o lodo e a sujeira do fundo\n4. Esfregar as paredes e o fundo com escova\n5. Conferir a boia e o registro\n6. Abrir o registro, encher e ver se não vaza", "m3": "Escova, balde e pá", "m4": "Luvas", "m5": "Bebedouros limpos, sem lodo e enchendo sozinhos", "meta_qtd": 10, "meta_unid": "Bebedouros", "tempo_h": 4, "checklist": ["Registro fechado antes de esvaziar", "Fundo sem lodo", "Paredes esfregadas", "Boia funcionando", "Enchendo e sem vazamento"]}'::jsonb),
  ('Cocho - Manutenção /Limpeza', 'Operacional', '2 - Estratégica', 2, '{true,true,true,true,true,true,false}'::boolean[], '{"m2": "1. Retirar a sobra velha, molhada ou mofada\n2. Varrer e raspar o fundo do cocho\n3. Conferir furos de escoamento e emendas\n4. Arrumar tábuas, telhado ou base soltos\n5. Anotar o que precisa de conserto maior", "m3": "Pá, enxada e vassoura", "m4": "Material de reparo (parafusos, tábuas)", "m5": "Cochos limpos e sem sobra estragada", "meta_qtd": 10, "meta_unid": "Cochos", "tempo_h": 3, "checklist": []}'::jsonb),
  ('Gado - Rodeio nos Lotes', 'Gado', '1 - Rotina', 2, '{false,true,true,true,true,false,false}'::boolean[], '{"m2": "1. Percorrer o pasto com calma, sem correr o gado\n2. Contar os animais de cada lote\n3. Observar animais mancando, magros, com bicheira ou isolados\n4. Conferir água, cocho, cerca e porteiras\n5. Anotar e avisar o líder sobre o que encontrou", "m3": "Cavalo ou moto", "m4": "Caderneta ou celular", "m5": "Todos os lotes contados e conferidos", "meta_qtd": 1, "meta_unid": "Rodeio Completo", "tempo_h": 4, "checklist": ["Contagem bateu com o lote", "Animais doentes ou machucados anotados", "Água conferida", "Cerca e porteiras conferidas"]}'::jsonb),
  ('Gado - Pesagem', 'Gado', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir e zerar a balança antes de começar\n2. Preparar o curral e o brete, sem pregos e sem buracos\n3. Trazer o lote com calma, sem cachorro e sem choque\n4. Pesar um animal por vez e anotar brinco e peso\n5. Conferir o total de animais pesados com o lote", "m3": "Balança, tronco e brete", "m4": "Planilha ou app, caneta, bastão marcador", "m5": "Lote pesado sem estresse e sem animal faltando", "meta_qtd": 100, "meta_unid": "Animais", "tempo_h": 3, "checklist": ["Balança zerada e aferida", "Curral e brete conferidos", "Brinco e peso de cada animal anotados", "Total pesado bate com o lote"]}'::jsonb),
  ('Gado - Apartação', 'Gerencial', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Combinar antes o critério da apartação (peso, sexo, idade, destino)\n2. Trazer o lote com calma até o curral\n3. Apartar no corredor um animal por vez\n4. Conferir a contagem de cada lote novo\n5. Levar cada lote ao pasto certo e anotar a mudança", "m3": "Curral com seringa e porteiras", "m4": "Lista dos lotes", "m5": "Lotes apartados conforme o critério, contagem conferida", "meta_qtd": 1, "meta_unid": "Lote", "tempo_h": 3, "checklist": []}'::jsonb),
  ('Gado - Embarque', 'Administrativo', '2 - Estratégica', 1, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir GTA, nota fiscal e a ordem de embarque\n2. Conferir o embarcadouro: limpo, sem pregos e sem buracos\n3. Conferir o caminhão: limpo e com piso firme\n4. Embarcar com calma, sem choque e sem pancada\n5. Contar os animais embarcados e conferir com a GTA\n6. Anotar a placa, o motorista e o horário de saída", "m3": "Embarcadouro e caminhão boiadeiro", "m4": "GTA, nota fiscal, bandeiras de manejo", "m5": "Embarque sem animal machucado e com a contagem certa", "meta_qtd": 1, "meta_unid": "Carga", "tempo_h": 2, "checklist": ["GTA e nota conferidas", "Embarcadouro sem pregos e buracos", "Caminhão limpo e com piso firme", "Manejo sem choque e sem pancada", "Contagem bate com a GTA", "Placa e horário anotados"]}'::jsonb),
  ('Gado - Identificação dos Animais', 'Administrativo', '2 - Estratégica', 1, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Separar o lote e conferir a lista de brincos\n2. Conter um animal por vez no tronco\n3. Aplicar o brinco na orelha certa, longe das veias\n4. Anotar o número do brinco e as informações do animal\n5. Soltar com calma e conferir o total", "m3": "Tronco de contenção, aplicador de brinco", "m4": "Brincos, desinfetante, planilha", "m5": "Todos os animais do lote brincados e anotados", "meta_qtd": 50, "meta_unid": "Animais", "tempo_h": 3, "checklist": []}'::jsonb),
  ('Gado - Combate de Carrapatos', 'Gado', '1 - Rotina', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir o produto, a dose e a carência na bula\n2. Preparar a calda certa ou a dose do pour-on\n3. Aplicar em todo o corpo, inclusive barriga, virilha e orelhas\n4. Anotar lote, produto, dose e data\n5. Lavar e guardar o equipamento e devolver a embalagem", "m3": "Pulverizador costal ou bomba, tronco", "m4": "Carrapaticida, EPI (luva, máscara, avental)", "m5": "Lote tratado com o produto e a dose certos", "meta_qtd": 1, "meta_unid": "Lote", "tempo_h": 3, "checklist": ["Produto e dose conferidos na bula", "EPI em uso", "Corpo todo tratado", "Lote e data anotados"]}'::jsonb),
  ('Gado - Combate Mosca - do - chifres', 'Gado', '1 - Rotina', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Avaliar a infestação (moscas por animal)\n2. Conferir o produto, a dose e a carência na bula\n3. Aplicar no lote todo, na região do dorso\n4. Anotar lote, produto e data\n5. Guardar o equipamento e devolver a embalagem", "m3": "Pulverizador ou aplicador pour-on", "m4": "Mosquicida, EPI", "m5": "Lote tratado e infestação controlada", "meta_qtd": 1, "meta_unid": "Lote", "tempo_h": 2, "checklist": []}'::jsonb),
  ('Gado - Vacinação Raiva', 'Gado', '2 - Estratégica', 1, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir a vacina: nome, lote e validade\n2. Manter a vacina na caixa térmica, entre 2 e 8 °C\n3. Regular a pistola na dose da bula\n4. Vacinar no local indicado na bula, trocando a agulha a cada lote\n5. Contar os animais vacinados e anotar\n6. Guardar a nota da vacina para o comprovante", "m3": "Tronco, pistola de vacinação", "m4": "Vacina, agulhas, caixa térmica com gelo", "m5": "Todo o rebanho previsto vacinado", "meta_qtd": 100, "meta_unid": "Animais", "tempo_h": 4, "checklist": ["Vacina na validade", "Caixa térmica entre 2 e 8 °C", "Pistola regulada na dose", "Agulhas trocadas", "Contagem de vacinados anotada", "Nota guardada"]}'::jsonb),
  ('Gado - Vacinação Carbunculo', 'Gado', '2 - Estratégica', 1, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir a vacina: nome, lote e validade\n2. Manter a vacina na caixa térmica, entre 2 e 8 °C\n3. Regular a pistola na dose da bula\n4. Vacinar no local indicado na bula, trocando a agulha a cada lote\n5. Contar os animais vacinados e anotar", "m3": "Tronco, pistola de vacinação", "m4": "Vacina, agulhas, caixa térmica com gelo", "m5": "Todos os animais da idade indicada vacinados", "meta_qtd": 100, "meta_unid": "Animais", "tempo_h": 4, "checklist": ["Vacina na validade", "Caixa térmica entre 2 e 8 °C", "Pistola regulada na dose", "Agulhas trocadas", "Contagem de vacinados anotada"]}'::jsonb),
  ('Gado - Vacinação Brucelose', 'Gado', '2 - Estratégica', 1, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Agendar o médico veterinário ou vacinador cadastrado\n2. Separar as fêmeas na idade exigida pela defesa sanitária\n3. Conferir a vacina: lote, validade e temperatura\n4. Vacinar e marcar conforme a regra do estado\n5. Guardar o atestado e comprovar no órgão de defesa no prazo", "m3": "Tronco, pistola", "m4": "Vacina, marcador, caixa térmica", "m5": "Todas as bezerras da idade vacinadas e comprovadas", "meta_qtd": 1, "meta_unid": "Lote", "tempo_h": 3, "checklist": ["Vacinador cadastrado presente", "Só fêmeas na idade exigida", "Vacina na validade e refrigerada", "Marcação feita", "Atestado guardado e comprovado"]}'::jsonb),
  ('Gado - Vermifugação', 'Gado', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir o produto, a dose por peso e a carência na bula\n2. Pesar ou estimar o peso do lote\n3. Regular a dose pelo animal mais pesado do lote\n4. Aplicar e marcar os animais já tratados\n5. Anotar lote, produto, dose e data", "m3": "Tronco, pistola dosadora", "m4": "Vermífugo, EPI, bastão marcador", "m5": "Lote vermifugado com a dose certa", "meta_qtd": 100, "meta_unid": "Animais", "tempo_h": 3, "checklist": ["Dose conferida pelo peso", "Animais tratados marcados", "Carência anotada", "Lote e data anotados"]}'::jsonb),
  ('Gado - Suplementação - Distribuição', 'Gado', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir o suplemento e a quantidade de cada lote\n2. Carregar o vagão ou o carrinho com a quantidade certa\n3. Distribuir de forma igual em todo o comprimento do cocho\n4. Anotar a quantidade entregue em cada lote\n5. Avisar se algum cocho estiver molhado, sujo ou quebrado", "m3": "Vagão forrageiro ou trator com carreta", "m4": "Suplemento, balança ou medida", "m5": "Quantidade certa entregue em todos os lotes", "meta_qtd": 1, "meta_unid": "Trato", "tempo_h": 2, "checklist": []}'::jsonb),
  ('Gado - Tirar Nota e GTA', 'Gerencial', '2 - Estratégica', 1, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir os animais que vão sair: quantidade, sexo e idade\n2. Conferir se as vacinas obrigatórias estão em dia\n3. Emitir a nota fiscal e a GTA\n4. Conferir os dados: destino, quantidade e finalidade\n5. Entregar uma cópia ao motorista e guardar outra", "m3": "Computador ou celular com internet", "m4": "Cadastro no órgão de defesa e na Sefaz", "m5": "GTA e nota emitidas antes do embarque, sem erro", "meta_qtd": 1, "meta_unid": "GTA", "tempo_h": 1, "checklist": []}'::jsonb),
  ('Cerca - Manutenção', 'Gado', '2 - Estratégica', 2, '{false,false,true,false,false,false,false}'::boolean[], '{"m2": "1. Percorrer a cerca do pasto inteiro\n2. Esticar os arames frouxos\n3. Trocar os arames rompidos e os grampos soltos\n4. Trocar ou escorar os palanques e esticadores podres ou caídos\n5. Anotar o que precisa de material a mais", "m3": "Esticador, alicate, cavadeira, marreta", "m4": "Arame, grampos, palanques e estacas", "m5": "Cerca do pasto inteiro firme, sem arame frouxo ou rompido", "meta_qtd": 1, "meta_unid": "Km de Cerca", "tempo_h": 6, "checklist": []}'::jsonb),
  ('Cerca Elétrica - Revisão do Choque', 'Geral', '1 - Rotina', 3, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Medir a voltagem na saída do aparelho e no ponto mais longe\n2. Procurar mato, galho ou arame encostando no fio\n3. Conferir isoladores quebrados e emendas\n4. Conferir o aterramento e a bateria ou placa solar\n5. Anotar a voltagem medida", "m3": "Voltímetro de cerca, alicate", "m4": "Isoladores, arame, emendas", "m5": "Choque acima do mínimo recomendado em toda a linha", "meta_qtd": 1, "meta_unid": "Linha", "tempo_h": 2, "checklist": ["Voltagem medida no aparelho", "Voltagem medida no ponto mais longe", "Linha sem mato encostando", "Aterramento conferido"]}'::jsonb),
  ('Curral - Manutenção', 'Gado', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Percorrer todo o curral: tábuas, porteiras, tronco, brete e embarcadouro\n2. Trocar tábuas quebradas e tirar pregos e pontas\n3. Conferir dobradiças, trincos e travas\n4. Tapar buracos e valetas do piso\n5. Anotar o que precisa de material a mais", "m3": "Martelo, furadeira, chave de boca", "m4": "Tábuas, parafusos, pregos", "m5": "Curral sem ponta, prego ou buraco que machuque o gado", "meta_qtd": 1, "meta_unid": "Curral", "tempo_h": 6, "checklist": []}'::jsonb),
  ('Curral / Baia - Limpeza', 'Gado', '1 - Rotina', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Raspar e retirar o esterco\n2. Juntar o esterco no local certo (esterqueira)\n3. Varrer corredores, brete e tronco\n4. Conferir bebedouro e cocho da baia\n5. Anotar o que estiver quebrado", "m3": "Pá carregadeira ou carrinho, rodo, vassoura", "m4": "Luvas e botas", "m5": "Curral limpo e sem acúmulo de esterco", "meta_qtd": 1, "meta_unid": "Curral", "tempo_h": 3, "checklist": []}'::jsonb),
  ('Porteira - Manutenção', 'Operacional', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir se a porteira abre e fecha sem arrastar\n2. Apertar ou trocar as dobradiças\n3. Trocar tábuas ou tubos quebrados\n4. Conferir o trinco e a corrente\n5. Conferir o mourão e a base", "m3": "Chave de boca, furadeira, cavadeira", "m4": "Dobradiças, parafusos, trincos", "m5": "Porteiras abrindo, fechando e travando bem", "meta_qtd": 5, "meta_unid": "Porteiras", "tempo_h": 3, "checklist": []}'::jsonb),
  ('Pasto - Manejo de Pastagens', 'Gado', '2 - Estratégica', 1, '{true,true,true,true,true,true,false}'::boolean[], '{"m2": "1. Medir a altura do capim na entrada e na saída de cada piquete\n2. Comparar com a altura certa para o capim\n3. Decidir a troca de pasto pelo capim, não pelo calendário\n4. Anotar a data de entrada e saída de cada lote\n5. Avisar se algum pasto precisa de vedação ou adubo", "m3": "Régua ou bastão medidor", "m4": "Planilha ou app", "m5": "Lotes trocados na altura certa do capim", "meta_qtd": 1, "meta_unid": "Rodada de Pastos", "tempo_h": 3, "checklist": []}'::jsonb),
  ('Pasto - Roçada de Pastos', 'Operacional', '2 - Estratégica', 2, '{true,true,true,true,true,false,false}'::boolean[], '{"m2": "1. Conferir a roçadeira: lâminas, graxa e cardan\n2. Tirar pedras, tocos e arames da área\n3. Roçar na altura combinada, sem rapar o capim\n4. Contornar cupins, tocos e cercas com cuidado\n5. Anotar a área roçada e as horas do trator", "m3": "Trator e roçadeira", "m4": "Graxa, óleo, EPI (protetor auricular e óculos)", "m5": "Área roçada na altura certa", "meta_qtd": 10, "meta_unid": "Hectares", "tempo_h": 8, "checklist": ["Roçadeira revisada (lâminas e graxa)", "Área conferida antes de roçar", "EPI em uso", "Hectares e horas anotados"]}'::jsonb),
  ('Pasto - Herbicida - Aplicação Foliar', 'Operacional', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir o produto, a dose e o receituário agronômico\n2. Conferir o tempo: sem chuva prevista, sem vento forte e sem calor forte\n3. Regular o pulverizador e conferir os bicos\n4. Aplicar sobre as folhas das plantas daninhas, sem deriva\n5. Lavar o equipamento, fazer a tríplice lavagem e guardar as embalagens\n6. Anotar área, produto, dose e data", "m3": "Pulverizador costal ou tratorizado", "m4": "Herbicida, EPI completo, água limpa", "m5": "Área aplicada na dose certa, sem deriva", "meta_qtd": 5, "meta_unid": "Hectares", "tempo_h": 6, "checklist": ["Receituário e dose conferidos", "Sem vento forte e sem chuva", "EPI completo em uso", "Bicos conferidos", "Tríplice lavagem feita", "Área e dose anotadas"]}'::jsonb),
  ('Pasto - Combate Formigas', 'Máquinas', '2 - Estratégica', 3, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Localizar os olheiros e carreiros ativos\n2. Aplicar a isca formicida ao lado do carreiro, sem pôr no olheiro\n3. Aplicar em tempo seco\n4. Não pegar a isca com a mão: usar dosador ou luva\n5. Voltar em 15 dias e conferir", "m3": "Dosador de isca", "m4": "Isca formicida, luvas", "m5": "Todos os formigueiros ativos tratados", "meta_qtd": 20, "meta_unid": "Formigueiros", "tempo_h": 4, "checklist": []}'::jsonb),
  ('Pasto - Combate Cupim', 'Máquinas', '2 - Estratégica', 3, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Marcar as áreas com mais cupinzeiros\n2. Furar o cupinzeiro até a câmara\n3. Aplicar o produto conforme a bula\n4. Tampar o furo\n5. Anotar a área e a quantidade tratada", "m3": "Furadeira de cupim ou barra de ferro", "m4": "Cupinicida, EPI", "m5": "Cupinzeiros da área tratados", "meta_qtd": 50, "meta_unid": "Cupinzeiros", "tempo_h": 6, "checklist": []}'::jsonb),
  ('Pasto - Calagem', 'Operacional', '2 - Estratégica', 3, '{true,true,true,true,true,false,false}'::boolean[], '{"m2": "1. Conferir a análise de solo e a recomendação de calcário\n2. Regular o distribuidor para a dose certa\n3. Aplicar em faixas, sem falha e sem sobreposição\n4. Anotar a área e as toneladas aplicadas\n5. Limpar o distribuidor no fim do dia", "m3": "Trator e distribuidor de calcário", "m4": "Calcário, EPI (máscara)", "m5": "Área corrigida na dose da recomendação", "meta_qtd": 20, "meta_unid": "Hectares", "tempo_h": 8, "checklist": []}'::jsonb),
  ('Pasto - Adubação', 'Máquinas', '2 - Estratégica', 3, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir a recomendação: produto, dose e época\n2. Aplicar com o solo úmido, no início das chuvas\n3. Regular a adubadeira para a dose certa\n4. Aplicar sem falha e sem sobreposição\n5. Anotar a área e a quantidade aplicada", "m3": "Trator e adubadeira", "m4": "Adubo, EPI", "m5": "Área adubada na dose e na época certas", "meta_qtd": 20, "meta_unid": "Hectares", "tempo_h": 8, "checklist": []}'::jsonb),
  ('Máquinas - Revisão', 'Máquinas', '2 - Estratégica', 1, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir o nível do óleo do motor e do hidráulico\n2. Conferir e limpar os filtros de ar, óleo e diesel\n3. Engraxar todos os pontos de lubrificação\n4. Conferir a água do radiador\n5. Conferir pneus, calibragem, correias e mangueiras\n6. Anotar o horímetro e o que foi trocado", "m3": "Chaves, engraxadeira, calibrador", "m4": "Óleo, filtros, graxa", "m5": "Máquina revisada conforme o manual, horímetro anotado", "meta_qtd": 1, "meta_unid": "Máquina", "tempo_h": 2, "checklist": ["Óleo do motor", "Filtros de ar, óleo e diesel", "Graxa nos pontos de lubrificação", "Água do radiador", "Pneus e calibragem", "Correias e mangueiras", "Horímetro anotado"]}'::jsonb),
  ('Máquinas - Limpeza', 'Máquinas', '2 - Estratégica', 3, '{true,false,false,false,false,true,false}'::boolean[], '{"m2": "1. Retirar o barro e o capim acumulados\n2. Limpar o radiador e a tela do filtro de ar\n3. Lavar sem jogar água direto no painel e na parte elétrica\n4. Engraxar depois de lavar\n5. Guardar na garagem ou na sombra", "m3": "Lava-jato ou mangueira, escova", "m4": "Detergente, graxa", "m5": "Máquina limpa, radiador desobstruído", "meta_qtd": 1, "meta_unid": "Máquina", "tempo_h": 2, "checklist": []}'::jsonb),
  ('Veículos - Revisão', 'Operacional', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir o óleo do motor e o fluido de freio\n2. Conferir a água do radiador\n3. Conferir pneus, estepe e calibragem\n4. Conferir luzes, setas e buzina\n5. Anotar a quilometragem e o que precisa de oficina", "m3": "Calibrador, chaves", "m4": "Óleo, água, fluidos", "m5": "Veículo seguro para rodar, km anotada", "meta_qtd": 1, "meta_unid": "Veículo", "tempo_h": 1, "checklist": ["Óleo do motor", "Freio", "Radiador", "Pneus e estepe", "Luzes e setas", "Km anotada"]}'::jsonb),
  ('Oficina - Organização', 'Máquinas', '2 - Estratégica', 3, '{true,true,true,true,true,true,false}'::boolean[], '{"m2": "1. Recolher as ferramentas espalhadas\n2. Guardar cada ferramenta no seu lugar marcado\n3. Separar peças usadas, sucata e lixo\n4. Limpar a bancada e o piso (óleo e graxa)\n5. Anotar ferramentas faltando ou quebradas", "m3": "Vassoura, rodo, pá", "m4": "Serragem para óleo, sacos de lixo", "m5": "Oficina organizada, cada ferramenta no lugar", "meta_qtd": 1, "meta_unid": "Oficina", "tempo_h": 3, "checklist": []}'::jsonb),
  ('Almoxarifado - Organização', 'Operacional', '1 - Rotina', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir o que entrou e saiu desde a última organização\n2. Guardar cada item no lugar marcado\n3. Separar produtos vencidos ou danificados\n4. Contar os itens principais e anotar no controle de estoque\n5. Avisar o que está acabando", "m3": "Prateleiras, etiquetas", "m4": "Planilha de estoque", "m5": "Almoxarifado organizado e estoque conferido", "meta_qtd": 1, "meta_unid": "Almoxarifado", "tempo_h": 3, "checklist": []}'::jsonb),
  ('Recebimento Diesel / Gasolina', 'Administrativo', '2 - Estratégica', 1, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir a nota fiscal: produto, quantidade e preço\n2. Medir o tanque antes de descarregar\n3. Acompanhar a descarga do começo ao fim\n4. Medir o tanque depois e conferir com a nota\n5. Anotar o recebimento no controle de abastecimento", "m3": "Régua de medição do tanque", "m4": "Planilha de controle", "m5": "Quantidade recebida igual à nota", "meta_qtd": 1, "meta_unid": "Recebimento", "tempo_h": 1, "checklist": ["Nota conferida", "Tanque medido antes", "Descarga acompanhada", "Tanque medido depois", "Diferença anotada"]}'::jsonb),
  ('Estrada - Manutenção', 'Operacional', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Percorrer a estrada e marcar buracos, valetas e atoleiros\n2. Patrolar ou raspar o leito, mantendo o abaulado\n3. Abrir ou limpar as saídas de água (bigodes)\n4. Cascalhar os pontos de atoleiro\n5. Anotar os km arrumados e as horas de máquina", "m3": "Patrol, pá carregadeira, caçamba", "m4": "Cascalho", "m5": "Estrada transitável e com escoamento de água", "meta_qtd": 2, "meta_unid": "Km de Estrada", "tempo_h": 8, "checklist": []}'::jsonb),
  ('Reservatório - Manutenção /Limpeza', 'Operacional', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Fechar a entrada de água e esvaziar\n2. Retirar o lodo e a sujeira do fundo\n3. Esfregar as paredes\n4. Conferir boia, registros e vazamentos\n5. Encher de novo e conferir a tampa", "m3": "Escova, pá, balde", "m4": "Luvas, botas", "m5": "Reservatório limpo e sem vazamento", "meta_qtd": 1, "meta_unid": "Reservatório", "tempo_h": 4, "checklist": []}'::jsonb),
  ('Sede - Lixo - Recolhimento', 'Operacional', '1 - Rotina', 2, '{false,false,false,false,false,true,false}'::boolean[], '{"m2": "1. Recolher o lixo das casas, do refeitório e da oficina\n2. Separar o lixo comum do reciclável\n3. Separar embalagens de produtos (veneno, remédio, óleo)\n4. Levar ao local certo de destino\n5. Manter a área do lixo limpa e fechada", "m3": "Carrinho ou caminhonete", "m4": "Sacos de lixo, luvas", "m5": "Sede sem lixo acumulado", "meta_qtd": 1, "meta_unid": "Coleta", "tempo_h": 2, "checklist": []}'::jsonb),
  ('Herbicidas - Devolução de Embalagens', 'Operacional', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir se todas as embalagens tiveram a tríplice lavagem e foram furadas\n2. Separar tampas e embalagens\n3. Contar e anotar as embalagens\n4. Levar ao posto de recebimento indicado na nota de compra\n5. Guardar o comprovante de devolução", "m3": "Caminhonete", "m4": "Sacos próprios, EPI", "m5": "Todas as embalagens devolvidas com comprovante", "meta_qtd": 1, "meta_unid": "Devolução", "tempo_h": 4, "checklist": ["Tríplice lavagem conferida", "Embalagens furadas", "Quantidade anotada", "Comprovante guardado"]}'::jsonb),
  ('Gestão - Pluviometro - Ler e Anotar', 'Administrativo', '1 - Rotina', 3, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Ler o pluviômetro todo dia no mesmo horário (7h)\n2. Anotar os milímetros e a data\n3. Esvaziar o pluviômetro depois de ler\n4. Lançar no app ou na planilha da fazenda", "m3": "Pluviômetro", "m4": "Planilha ou app", "m5": "Chuva anotada todos os dias", "meta_qtd": 1, "meta_unid": "Leitura", "tempo_h": 0.1, "checklist": []}'::jsonb),
  ('Gestão - Reunião Semanal - 20 min', 'Gerencial', '1 - Rotina', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Começar no horário, em pé, no mesmo local\n2. Ver o que foi feito e o que atrasou na semana\n3. Combinar as prioridades da próxima semana\n4. Cada líder fala um compromisso\n5. Anotar os compromissos no sistema", "m3": "Painel do Dia ou Tarefas da Semana na tela", "m4": "Lista de compromissos", "m5": "Reunião de 20 minutos com compromissos anotados", "meta_qtd": 1, "meta_unid": "Reunião", "tempo_h": 0.4, "checklist": []}'::jsonb)
) as m(nome, setor, tipo, urg, dias, cf)
on conflict (conta_id, chave) do update
  set como_fazer = excluded.como_fazer
  where coalesce(biblioteca.como_fazer->>'m2', '') = '';

select count(*) filter (where coalesce(como_fazer->>'m2', '') <> '') || ' de ' || count(*) || ' atividades da Biblioteca têm 5M' as resultado
from biblioteca;
