-- =====================================================================
-- FARM PLAN · Gesta'Up · 033 · Biblioteca com 5M Pronto (Parte 2)
-- Mais 49 atividades com 5M e Lista de Conferência: confinamento,
-- fábrica, tropa, cerca elétrica, cocho, pasto, volumoso, máquinas,
-- água, sede e gestão. Junto com o 032, são 89 atividades.
--  · Atividade que já está na Biblioteca SEM 5M: recebe o 5M.
--  · Atividade que já tem 5M na Biblioteca: NÃO é alterada.
--  · Atividade que não existe: é criada.
-- Não mexe nas fazendas. Nelas, use Cadastros › 5M das Atividades ›
-- 📚 Puxar o 5M da Biblioteca.
-- Pode rodar mais de uma vez sem problema.
-- Rodar: Supabase › SQL Editor › New query › colar › Run.
-- =====================================================================
insert into biblioteca (conta_id, nome, setor_nome, tipo, urgencia, dias, como_fazer, origem)
select c.id, m.nome, m.setor, m.tipo, m.urg, m.dias, m.cf, 'Biblioteca Gesta''Up'
from contas c
cross join (values
  ('Confinamento - Tratar dos Animais', 'Gado', '1 - Rotina', 1, '{true,true,true,true,true,true,true}'::boolean[], '{"m2": "1. Conferir a leitura de cocho e a quantidade de cada baia\n2. Carregar o vagão seguindo a ordem e o peso de cada ingrediente da receita\n3. Misturar pelo tempo certo\n4. Distribuir de forma igual em todo o cocho, sempre nos mesmos horários\n5. Anotar o fornecido de cada baia e avisar sobra ou falta", "m3": "Vagão misturador e trator ou pá carregadeira", "m4": "Receita da dieta, planilha de trato", "m5": "Todas as baias tratadas no horário e na quantidade certa", "meta_qtd": 1, "meta_unid": "Trato", "tempo_h": 3, "checklist": ["Leitura de cocho conferida", "Ingredientes pesados conforme a receita", "Tempo de mistura cumprido", "Fornecido anotado por baia"]}'::jsonb),
  ('Confinamento - Molhar Curral (pipa)', 'Operacional', '1 - Rotina', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Encher o pipa com água\n2. Molhar os corredores e as baias com mais poeira\n3. Não encharcar a área do cocho\n4. Repetir nas horas mais secas, se precisar\n5. Anotar quantas cargas foram usadas", "m3": "Trator e pipa", "m4": "Água", "m5": "Curral sem poeira forte", "meta_qtd": 1, "meta_unid": "Rodada", "tempo_h": 2, "checklist": []}'::jsonb),
  ('Gado - Suplementação Fornecimento', 'Máquinas', '1 - Rotina', 1, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir o suplemento e a quantidade de cada lote na lista do dia\n2. Pesar ou medir a quantidade de cada lote\n3. Entregar no cocho sempre no mesmo horário\n4. Conferir se o cocho estava limpo e seco\n5. Anotar o entregue em cada lote", "m3": "Trator com carreta ou vagão", "m4": "Suplemento, balança", "m5": "Todos os lotes suplementados na quantidade certa", "meta_qtd": 1, "meta_unid": "Rodada", "tempo_h": 3, "checklist": []}'::jsonb),
  ('Produzir Ração_ Suplemento', 'Operacional', '1 - Rotina', 1, '{true,true,true,true,true,true,true}'::boolean[], '{"m2": "1. Conferir a receita e o estoque de cada ingrediente\n2. Pesar cada ingrediente na balança\n3. Misturar pelo tempo indicado\n4. Ensacar ou guardar em local seco e identificado\n5. Anotar a quantidade produzida, a receita e a data", "m3": "Misturador, balança", "m4": "Ingredientes da receita, sacaria", "m5": "Lote de ração produzido na receita certa", "meta_qtd": 1, "meta_unid": "Lote", "tempo_h": 3, "checklist": ["Receita conferida", "Ingredientes pesados", "Tempo de mistura cumprido", "Produção anotada"]}'::jsonb),
  ('Gado - Auditoria do Rebanho', 'Gado', '2 - Estratégica', 1, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Pegar a lista do rebanho no sistema ou planilha\n2. Contar cada lote no curral ou no pasto\n3. Conferir categoria (sexo e idade) e brincos\n4. Anotar diferenças: mortes, nascimentos, transferências\n5. Acertar o estoque e explicar as diferenças", "m3": "Curral, cavalo ou moto", "m4": "Lista do rebanho, caneta", "m5": "Rebanho contado e estoque batendo com o sistema", "meta_qtd": 1, "meta_unid": "Auditoria", "tempo_h": 6, "checklist": []}'::jsonb),
  ('Gado - Evolução do Rebanho/Indea', 'Gerencial', '2 - Estratégica', 1, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Juntar os nascimentos, mortes, compras, vendas e mudanças de categoria do período\n2. Lançar a evolução do rebanho\n3. Conferir com o saldo do órgão de defesa\n4. Atualizar a declaração de rebanho no prazo\n5. Guardar o comprovante", "m3": "Computador com internet", "m4": "Relatórios do rebanho, senha do órgão de defesa", "m5": "Saldo do órgão de defesa igual ao da fazenda", "meta_qtd": 1, "meta_unid": "Atualização", "tempo_h": 2, "checklist": []}'::jsonb),
  ('Gado - Compra de Animais', 'Gerencial', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Definir categoria, quantidade, peso e preço máximo\n2. Conferir a origem: sanidade, GTA e vacinas\n3. Pesar ou conferir o peso na chegada\n4. Fazer a quarentena e o manejo de entrada (vermífugo, vacinas, brinco)\n5. Lançar a compra no rebanho e no financeiro", "m3": "Balança, curral", "m4": "GTA, nota fiscal, planilha", "m5": "Animais comprados dentro do combinado e lançados", "meta_qtd": 1, "meta_unid": "Compra", "tempo_h": 4, "checklist": []}'::jsonb),
  ('Auditoria - conferência de estoque medicamentos', 'Operacional', '4 - Estruturação', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Listar os medicamentos e vacinas do estoque\n2. Contar cada item e conferir a validade\n3. Conferir a temperatura da geladeira das vacinas\n4. Separar os vencidos para descarte certo\n5. Atualizar o controle e avisar o que precisa comprar", "m3": "Geladeira, termômetro", "m4": "Planilha de estoque", "m5": "Estoque contado e sem produto vencido no uso", "meta_qtd": 1, "meta_unid": "Conferência", "tempo_h": 2, "checklist": ["Itens contados", "Validades conferidas", "Temperatura da geladeira anotada", "Vencidos separados", "Controle atualizado"]}'::jsonb),
  ('Fábrica - Limpeza', 'Operacional', '1 - Rotina', 2, '{false,false,false,true,false,false,false}'::boolean[], '{"m2": "1. Desligar as máquinas antes de limpar\n2. Varrer e retirar restos de ração e poeira\n3. Limpar o misturador e as roscas\n4. Conferir sinais de rato, inseto ou umidade\n5. Deixar os ingredientes fechados e identificados", "m3": "Vassoura, pá, soprador", "m4": "EPI (máscara), sacos", "m5": "Fábrica limpa e sem ração velha acumulada", "meta_qtd": 1, "meta_unid": "Limpeza", "tempo_h": 3, "checklist": []}'::jsonb),
  ('Fabrica - Manutenção', 'Operacional', '1 - Rotina', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Desligar e travar a energia antes de mexer\n2. Conferir correias, rolamentos e roscas\n3. Engraxar os pontos de lubrificação\n4. Conferir a balança e a parte elétrica\n5. Anotar peças trocadas e o que precisa comprar", "m3": "Chaves, engraxadeira", "m4": "Graxa, correias, peças", "m5": "Fábrica funcionando sem parada por quebra", "meta_qtd": 1, "meta_unid": "Manutenção", "tempo_h": 3, "checklist": ["Energia desligada e travada", "Correias e rolamentos", "Graxa nos pontos", "Balança conferida"]}'::jsonb),
  ('Tropa - Trato Ração', 'Gado', '1 - Rotina', 2, '{true,true,true,true,true,true,false}'::boolean[], '{"m2": "1. Conferir a quantidade de ração de cada animal\n2. Tratar sempre nos mesmos horários\n3. Conferir a água do cocho\n4. Observar se algum animal não comeu\n5. Anotar e avisar o que estiver fora do normal", "m3": "Balde, medida", "m4": "Ração", "m5": "Tropa tratada no horário e na quantidade certa", "meta_qtd": 1, "meta_unid": "Trato", "tempo_h": 0.5, "checklist": []}'::jsonb),
  ('Tropa - Casqueamento', 'Gado', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Amarrar e conter o animal com segurança\n2. Limpar o casco\n3. Aparar e nivelar o casco\n4. Conferir ferradura, se tiver\n5. Anotar o animal e a data", "m3": "Torquês, grosa, rinete", "m4": "Ferraduras e cravos, se precisar", "m5": "Animais com casco aparado e sem mancar", "meta_qtd": 5, "meta_unid": "Animais", "tempo_h": 3, "checklist": []}'::jsonb),
  ('Tropa_Vermifugação e Vacinação', 'Gado', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir os produtos, as doses por peso e a validade\n2. Conter o animal com segurança\n3. Aplicar o vermífugo e as vacinas conforme a bula\n4. Anotar animal, produto e data\n5. Marcar a próxima data", "m3": "Seringas, pistola", "m4": "Vermífugo, vacinas, caixa térmica", "m5": "Tropa tratada e com as datas anotadas", "meta_qtd": 1, "meta_unid": "Tropa", "tempo_h": 2, "checklist": ["Produtos e doses conferidos", "Vacina refrigerada", "Animais anotados", "Próxima data marcada"]}'::jsonb),
  ('Tropa - Combate de Carrapatos', 'Gado', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir o produto e a dose na bula\n2. Aplicar no corpo todo, inclusive orelhas e entre as pernas\n3. Anotar animal, produto e data\n4. Guardar o equipamento e devolver a embalagem", "m3": "Pulverizador costal", "m4": "Carrapaticida, EPI", "m5": "Tropa tratada com o produto e a dose certos", "meta_qtd": 1, "meta_unid": "Tropa", "tempo_h": 1, "checklist": []}'::jsonb),
  ('Bebedouros - Instalação /Manutenção', 'Operacional', '1 - Rotina', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir o nível do terreno e a base do bebedouro\n2. Instalar ou trocar boia, registro e cano\n3. Vedar emendas e conferir vazamentos\n4. Proteger o bebedouro contra o pisoteio (base firme ou cascalho)\n5. Encher e testar a boia", "m3": "Chaves, serra, enxada", "m4": "Boia, registro, canos, conexões, veda-rosca", "m5": "Bebedouro funcionando, sem vazamento e com boia regulada", "meta_qtd": 2, "meta_unid": "Bebedouros", "tempo_h": 4, "checklist": []}'::jsonb),
  ('Cerca - Construção', 'Gado', '4 - Estruturação', 1, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Marcar o alinhamento com estacas e linha\n2. Abrir os buracos dos esticadores e palanques no espaço combinado\n3. Firmar esticadores e palanques bem socados\n4. Passar e esticar os fios na altura certa\n5. Grampear e conferir a tensão de todos os fios", "m3": "Cavadeira, esticador, marreta, alicate", "m4": "Arame, palanques, esticadores, grampos", "m5": "Cerca nova firme e alinhada", "meta_qtd": 500, "meta_unid": "Metros", "tempo_h": 8, "checklist": []}'::jsonb),
  ('Cerca Elétrica - Construção', 'Gado', '4 - Estruturação', 3, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Marcar o alinhamento e limpar a faixa\n2. Fincar as estacas e os cantos firmes\n3. Instalar isoladores e passar o fio na altura certa\n4. Fazer o aterramento conforme o aparelho\n5. Ligar e medir a voltagem no ponto mais longe", "m3": "Cavadeira, marreta, voltímetro", "m4": "Fio, isoladores, estacas, hastes de aterramento", "m5": "Cerca elétrica com choque em toda a linha", "meta_qtd": 1, "meta_unid": "Km", "tempo_h": 8, "checklist": []}'::jsonb),
  ('Cerca Elétrica - Aceiro / Manutenção', 'Gado', '4 - Estruturação', 3, '{false,false,true,false,false,false,false}'::boolean[], '{"m2": "1. Roçar ou capinar a faixa embaixo do fio\n2. Retirar galhos e mato encostando no fio\n3. Trocar isoladores quebrados\n4. Esticar o fio e refazer emendas ruins\n5. Medir a voltagem depois do serviço", "m3": "Roçadeira costal, alicate, voltímetro", "m4": "Isoladores, fio, emendas", "m5": "Linha limpa e com choque", "meta_qtd": 1, "meta_unid": "Km", "tempo_h": 4, "checklist": []}'::jsonb),
  ('Cerca Elétrica - Placa Solar', 'Máquinas', '4 - Estruturação', 3, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Limpar a placa com pano e água, sem produto abrasivo\n2. Conferir os cabos e as conexões\n3. Conferir a carga da bateria\n4. Conferir se a placa está virada para o sol, sem sombra\n5. Medir a voltagem da cerca depois", "m3": "Pano, balde, multímetro", "m4": "Água limpa", "m5": "Placa limpa e bateria carregando", "meta_qtd": 1, "meta_unid": "Placa", "tempo_h": 1, "checklist": []}'::jsonb),
  ('Cerca - Aceiro (gradagem) /(herbicida)', 'Máquinas', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Marcar a faixa de aceiro ao longo da cerca\n2. Gradear ou aplicar o herbicida na largura combinada\n3. Não encostar a grade nos palanques\n4. Conferir se a faixa ficou contínua, sem falhas\n5. Anotar os metros feitos", "m3": "Trator e grade, ou pulverizador", "m4": "Herbicida (se for o caso), EPI", "m5": "Aceiro contínuo na largura certa", "meta_qtd": 2, "meta_unid": "Km", "tempo_h": 6, "checklist": []}'::jsonb),
  ('Cocho - Construção e Montagem', 'Operacional', '4 - Estruturação', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Escolher local alto, firme e de fácil acesso\n2. Montar a base e nivelar\n3. Montar o cocho e a cobertura, se tiver\n4. Fazer os furos de escoamento\n5. Calcular o espaço de cocho por animal", "m3": "Furadeira, serra, nível", "m4": "Material do cocho, parafusos", "m5": "Cocho montado, nivelado e com escoamento", "meta_qtd": 2, "meta_unid": "Cochos", "tempo_h": 6, "checklist": []}'::jsonb),
  ('Cocho - Cascalhamento', 'Gado', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Raspar o barro em volta do cocho\n2. Espalhar o cascalho na volta toda\n3. Compactar o cascalho\n4. Deixar caimento para a água escorrer\n5. Anotar os cochos feitos", "m3": "Pá carregadeira, caçamba", "m4": "Cascalho", "m5": "Volta do cocho firme e sem barro", "meta_qtd": 4, "meta_unid": "Cochos", "tempo_h": 6, "checklist": []}'::jsonb),
  ('Curral - Manutenção Tronco de Contenção', 'Operacional', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir a pescoceira, as portas e as travas\n2. Engraxar as partes móveis\n3. Apertar parafusos e trocar peças gastas\n4. Conferir o piso antiderrapante\n5. Testar com um animal antes do manejo", "m3": "Chaves, engraxadeira", "m4": "Graxa, parafusos, peças", "m5": "Tronco seguro e funcionando", "meta_qtd": 1, "meta_unid": "Tronco", "tempo_h": 2, "checklist": []}'::jsonb),
  ('Porteira - Construção', 'Gado', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Marcar o local e a largura da porteira\n2. Fincar e firmar os mourões no prumo\n3. Instalar as dobradiças e a porteira no nível\n4. Instalar o trinco ou a corrente\n5. Testar abrir e fechar", "m3": "Cavadeira, nível, furadeira", "m4": "Mourões, porteira, dobradiças, trinco", "m5": "Porteira firme, no nível e fechando bem", "meta_qtd": 2, "meta_unid": "Porteiras", "tempo_h": 6, "checklist": []}'::jsonb),
  ('Pasto - Herbicida - Aplicação Basal', 'Máquinas', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir o produto, a dose e o receituário agronômico\n2. Aplicar na base do tronco das plantas daninhas, em volta toda\n3. Não aplicar com chuva prevista\n4. Marcar as plantas tratadas para não repetir\n5. Anotar a área, o produto e a quantidade usada", "m3": "Pulverizador costal", "m4": "Herbicida, óleo (se a bula pedir), EPI completo", "m5": "Plantas da área tratadas na dose certa", "meta_qtd": 5, "meta_unid": "Hectares", "tempo_h": 6, "checklist": ["Receituário e dose conferidos", "EPI completo em uso", "Sem chuva prevista", "Área anotada"]}'::jsonb),
  ('Pasto - Herbicida - Revisão Pulverizador', 'Máquinas', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Lavar o tanque e as mangueiras\n2. Conferir e limpar os bicos e os filtros\n3. Trocar bicos gastos (vazão diferente)\n4. Conferir mangueiras, vedações e o manômetro\n5. Calibrar a vazão com água antes de usar", "m3": "Chaves, proveta, cronômetro", "m4": "Bicos, filtros, vedações", "m5": "Pulverizador calibrado e sem vazamento", "meta_qtd": 1, "meta_unid": "Pulverizador", "tempo_h": 2, "checklist": ["Tanque lavado", "Bicos e filtros limpos", "Bicos gastos trocados", "Sem vazamento", "Vazão calibrada"]}'::jsonb),
  ('Pasto - Inseticida - Aplicação Cigarrinhas', 'Máquinas', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Avaliar a infestação nos pastos (espuma na base do capim)\n2. Conferir o produto, a dose e o receituário\n3. Aplicar nas horas mais frescas, sem vento\n4. Respeitar a carência antes de voltar o gado\n5. Anotar a área e a data", "m3": "Pulverizador", "m4": "Inseticida, EPI", "m5": "Área tratada e carência respeitada", "meta_qtd": 10, "meta_unid": "Hectares", "tempo_h": 6, "checklist": []}'::jsonb),
  ('Pasto - Limpeza (Ossos, Lascas, Galhos,Pedras,Arame)', 'Geral', '2 - Estratégica', 3, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Percorrer o pasto em faixas\n2. Recolher ossos, galhos, pedras, lascas e arame solto\n3. Juntar tudo na carreta\n4. Levar ao local de descarte\n5. Anotar os pastos limpos", "m3": "Trator com carreta", "m4": "Luvas", "m5": "Pasto limpo, sem risco para o gado e para as máquinas", "meta_qtd": 10, "meta_unid": "Hectares", "tempo_h": 6, "checklist": []}'::jsonb),
  ('Pasto - Gradagem de Pastagem', 'Máquinas', '2 - Estratégica', 2, '{false,false,false,true,true,true,false}'::boolean[], '{"m2": "1. Conferir a umidade do solo (nem seco demais, nem encharcado)\n2. Regular a grade na profundidade combinada\n3. Gradear em nível, acompanhando o terreno\n4. Contornar cupins e tocos\n5. Anotar a área e as horas", "m3": "Trator e grade", "m4": "Graxa, EPI", "m5": "Área gradeada na profundidade certa", "meta_qtd": 10, "meta_unid": "Hectares", "tempo_h": 8, "checklist": []}'::jsonb),
  ('Pasto - Manutenção de Represas', 'Operacional', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir o talude e o vertedouro\n2. Retirar o mato do talude\n3. Tapar buracos de tatu e erosões\n4. Desentupir o vertedouro\n5. Anotar o nível da água", "m3": "Enxada, roçadeira", "m4": "Terra para aterro", "m5": "Represa sem vazamento e com vertedouro livre", "meta_qtd": 1, "meta_unid": "Represa", "tempo_h": 4, "checklist": []}'::jsonb),
  ('Pasto - Plantio Lavoura / Silo / Capim', 'Máquinas', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir o preparo do solo e a umidade\n2. Regular a plantadeira para a semente e a quantidade\n3. Plantar em nível\n4. Conferir a profundidade e a distribuição no começo\n5. Anotar a área, a semente e a quantidade usada", "m3": "Trator e plantadeira", "m4": "Sementes, adubo", "m5": "Área plantada com estande uniforme", "meta_qtd": 10, "meta_unid": "Hectares", "tempo_h": 8, "checklist": []}'::jsonb),
  ('Volumoso - Ensilagem', 'Máquinas', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir o ponto de colheita da lavoura\n2. Regular a ensiladeira no tamanho de partícula certo\n3. Encher o silo em camadas finas e compactar bem\n4. Fechar e vedar o silo no mesmo dia\n5. Anotar as toneladas e a data", "m3": "Ensiladeira, carretas, trator de compactação", "m4": "Lona, peso para lona", "m5": "Silo bem compactado e vedado no mesmo dia", "meta_qtd": 1, "meta_unid": "Silo", "tempo_h": 10, "checklist": ["Ponto de colheita conferido", "Tamanho de partícula regulado", "Camadas compactadas", "Silo vedado no mesmo dia"]}'::jsonb),
  ('Silo - Cerca / cobrir monte / Manutenção', 'Operacional', '4 - Estruturação', 1, '{true,true,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir furos e rasgos na lona\n2. Remendar a lona\n3. Colocar peso em cima da lona (pneus ou terra)\n4. Conferir a cerca em volta do silo\n5. Manter a área limpa, sem mato e sem rato", "m3": "Alicate", "m4": "Fita para lona, pneus, arame", "m5": "Silo vedado e protegido", "meta_qtd": 1, "meta_unid": "Silo", "tempo_h": 2, "checklist": []}'::jsonb),
  ('Erosão - Contenção', 'Máquinas', '2 - Estratégica', 1, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Marcar a erosão e de onde vem a água\n2. Desviar a água com curva de nível ou bigode\n3. Aterrar e compactar o buraco\n4. Plantar capim ou cobrir o solo\n5. Voltar depois da próxima chuva e conferir", "m3": "Pá carregadeira, patrol", "m4": "Terra, sementes de capim", "m5": "Erosão contida e água desviada", "meta_qtd": 1, "meta_unid": "Erosão", "tempo_h": 6, "checklist": []}'::jsonb),
  ('Máquinas - Manutenção', 'Máquinas', '2 - Estratégica', 3, '{false,false,false,false,true,false,false}'::boolean[], '{"m2": "1. Anotar o defeito que o operador relatou\n2. Conferir a causa antes de trocar peça\n3. Fazer o conserto ou chamar a oficina\n4. Testar a máquina depois do conserto\n5. Anotar peças trocadas, custo e horímetro", "m3": "Ferramentas da oficina", "m4": "Peças, óleo, graxa", "m5": "Máquina consertada e testada", "meta_qtd": 1, "meta_unid": "Máquina", "tempo_h": 4, "checklist": []}'::jsonb),
  ('Implementos - Organização/ Manutenção', 'Máquinas', '2 - Estratégica', 2, '{true,true,true,true,true,false,false}'::boolean[], '{"m2": "1. Guardar cada implemento no lugar dele, na sombra\n2. Engraxar e conferir rolamentos\n3. Conferir lâminas, discos e pinos\n4. Trocar o que estiver gasto ou quebrado\n5. Anotar o que precisa de peça", "m3": "Engraxadeira, chaves", "m4": "Graxa, pinos, peças", "m5": "Implementos guardados e prontos para usar", "meta_qtd": 4, "meta_unid": "Implementos", "tempo_h": 4, "checklist": []}'::jsonb),
  ('Oficina - Limpeza', 'Máquinas', '2 - Estratégica', 3, '{false,false,false,false,false,true,false}'::boolean[], '{"m2": "1. Recolher estopas, latas e peças velhas\n2. Jogar serragem no óleo do chão e varrer\n3. Limpar bancada e ferramentas\n4. Separar o óleo usado no tambor certo\n5. Deixar o lixo separado para o descarte", "m3": "Vassoura, pá", "m4": "Serragem, sacos", "m5": "Oficina limpa e sem óleo no chão", "meta_qtd": 1, "meta_unid": "Oficina", "tempo_h": 2, "checklist": []}'::jsonb),
  ('Veículos - Limpeza', 'Gerencial', '2 - Estratégica', 2, '{false,false,false,false,false,true,false}'::boolean[], '{"m2": "1. Retirar o lixo de dentro\n2. Lavar por fora, inclusive a parte de baixo\n3. Limpar o painel e os bancos\n4. Conferir se não ficou ferramenta solta\n5. Guardar na garagem", "m3": "Mangueira ou lava-jato", "m4": "Detergente, panos", "m5": "Veículo limpo por dentro e por fora", "meta_qtd": 1, "meta_unid": "Veículo", "tempo_h": 1, "checklist": []}'::jsonb),
  ('Vagão - Limpeza', 'Máquinas', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Esvaziar a sobra de ração\n2. Lavar a caixa e as roscas\n3. Retirar ração grudada e mofada\n4. Conferir as facas e a balança do vagão\n5. Engraxar depois de lavar", "m3": "Lava-jato, raspador", "m4": "Graxa", "m5": "Vagão limpo, sem ração velha", "meta_qtd": 1, "meta_unid": "Vagão", "tempo_h": 2, "checklist": []}'::jsonb),
  ('Vagão - Manutenção', 'Máquinas', '2 - Estratégica', 2, '{false,false,false,true,false,false,false}'::boolean[], '{"m2": "1. Conferir correntes, roscas e facas\n2. Engraxar todos os pontos\n3. Conferir a balança do vagão com um peso conhecido\n4. Conferir o cardan e os pneus\n5. Anotar peças trocadas", "m3": "Engraxadeira, chaves", "m4": "Graxa, peças", "m5": "Vagão funcionando e balança aferida", "meta_qtd": 1, "meta_unid": "Vagão", "tempo_h": 3, "checklist": ["Correntes e roscas", "Facas", "Graxa", "Balança aferida", "Cardan e pneus"]}'::jsonb),
  ('Poço Artesiano - Manutenção', 'Operacional', '4 - Estruturação', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Conferir a bomba, o quadro elétrico e o horímetro\n2. Conferir a vazão e se tem barulho ou vibração\n3. Conferir a tampa do poço e a área em volta\n4. Limpar a área e tirar o mato\n5. Anotar o horímetro e o que encontrou", "m3": "Multímetro, chaves", "m4": "EPI", "m5": "Poço funcionando e protegido", "meta_qtd": 1, "meta_unid": "Poço", "tempo_h": 2, "checklist": []}'::jsonb),
  ('Rede Hidraulica - Manutenção - Instalação', 'Operacional', '2 - Estratégica', 3, '{false,true,false,true,false,false,false}'::boolean[], '{"m2": "1. Percorrer a rede procurando vazamentos\n2. Fechar o registro antes do conserto\n3. Trocar canos e conexões danificados\n4. Testar a pressão depois do conserto\n5. Anotar onde foi o conserto", "m3": "Serra, chaves, enxada", "m4": "Canos, conexões, cola, veda-rosca", "m5": "Rede sem vazamento", "meta_qtd": 1, "meta_unid": "Rodada", "tempo_h": 4, "checklist": []}'::jsonb),
  ('Reservatório - Monitoramento do Nível', 'Gerencial', '2 - Estratégica', 2, '{true,true,true,true,true,true,true}'::boolean[], '{"m2": "1. Ler o nível do reservatório no mesmo horário\n2. Anotar o nível\n3. Conferir se a bomba está ligando e desligando certo\n4. Avisar se o nível estiver baixando fora do normal", "m3": "Régua ou boia de nível", "m4": "Planilha ou app", "m5": "Nível anotado todos os dias", "meta_qtd": 1, "meta_unid": "Leitura", "tempo_h": 0.2, "checklist": []}'::jsonb),
  ('Alojamento - Limpeza - Manutenção', 'Geral', '1 - Rotina', 2, '{false,false,false,true,false,false,false}'::boolean[], '{"m2": "1. Varrer e lavar quartos, banheiros e cozinha\n2. Recolher o lixo\n3. Conferir lâmpadas, tomadas, chuveiro e torneiras\n4. Anotar consertos necessários\n5. Manter a área externa limpa", "m3": "Vassoura, rodo, balde", "m4": "Produtos de limpeza", "m5": "Alojamento limpo e sem conserto pendente", "meta_qtd": 1, "meta_unid": "Alojamento", "tempo_h": 3, "checklist": []}'::jsonb),
  ('Sede - Roçar a Grama', 'Operacional', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Retirar pedras e objetos do gramado\n2. Conferir a roçadeira e o combustível\n3. Roçar na altura combinada\n4. Varrer ou rastelar a grama cortada\n5. Limpar e guardar a roçadeira", "m3": "Roçadeira costal ou cortador", "m4": "Combustível, fio de nylon, EPI (óculos e protetor)", "m5": "Gramado da sede aparado", "meta_qtd": 1, "meta_unid": "Gramado", "tempo_h": 3, "checklist": []}'::jsonb),
  ('Sede - Limpeza Placa Solar', 'Administrativo', '2 - Estratégica', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Limpar as placas com pano e água, sem produto abrasivo\n2. Fazer de manhã cedo ou no fim da tarde\n3. Conferir cabos e conexões\n4. Anotar a geração do inversor antes e depois", "m3": "Escada, pano, rodo macio", "m4": "Água limpa, EPI (cinto se for no telhado)", "m5": "Placas limpas", "meta_qtd": 1, "meta_unid": "Limpeza", "tempo_h": 2, "checklist": ["Escada firme e cinto em uso", "Sem produto abrasivo", "Geração anotada"]}'::jsonb),
  ('Depósito de Defensivos - Limpeza e organização', 'Gerencial', '5 - Projeto', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Usar EPI completo\n2. Organizar os produtos por tipo, com o rótulo para frente\n3. Separar embalagens vazias para a tríplice lavagem e devolução\n4. Conferir vazamentos e limpar com material absorvente\n5. Manter o depósito trancado e com placa de aviso", "m3": "Prateleiras, pá", "m4": "Material absorvente, EPI completo", "m5": "Depósito organizado, sem vazamento e trancado", "meta_qtd": 1, "meta_unid": "Depósito", "tempo_h": 2, "checklist": ["EPI completo em uso", "Produtos organizados", "Embalagens vazias separadas", "Sem vazamento", "Depósito trancado"]}'::jsonb),
  ('Gestão - Reunião Mensal - 1 hora', 'Gerencial', '1 - Rotina', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Começar no horário, com o Painel do mês na tela\n2. Ver as metas e os indicadores do mês\n3. Ver o que deu certo e o que travou\n4. Combinar as prioridades do próximo mês\n5. Anotar os compromissos e quem cuida de cada um", "m3": "Computador ou TV com o Farm Plan", "m4": "Relatório Mensal, indicadores", "m5": "Reunião de 1 hora com prioridades e responsáveis anotados", "meta_qtd": 1, "meta_unid": "Reunião", "tempo_h": 1, "checklist": []}'::jsonb),
  ('Reunião Geral', 'Administrativo', '3 - Gestão', 2, '{true,false,false,false,false,false,false}'::boolean[], '{"m2": "1. Avisar a equipe com antecedência\n2. Começar no horário\n3. Passar os resultados e os recados\n4. Ouvir a equipe\n5. Anotar os combinados", "m3": "Local para todos sentados", "m4": "Pauta", "m5": "Equipe informada e combinados anotados", "meta_qtd": 1, "meta_unid": "Reunião", "tempo_h": 1, "checklist": []}'::jsonb)
) as m(nome, setor, tipo, urg, dias, cf)
on conflict (conta_id, chave) do update
  set como_fazer = excluded.como_fazer
  where coalesce(biblioteca.como_fazer->>'m2', '') = '';

select count(*) filter (where coalesce(como_fazer->>'m2', '') <> '') || ' de ' || count(*) || ' atividades da Biblioteca têm 5M' as resultado
from biblioteca;
