-- Farm Plan · Conferir a Configuração (só lê, não muda nada)
with c(ordem, item, ok, se_faltar) as (values
 (1, 'SQL 024 · Consultores', to_regclass('public.consultores') is not null and to_regprocedure('public.minha_conta()') is not null, 'Rodar o arquivo 024_consultores_da_equipe.sql'),
 (2, 'SQL 025 · Avisos no Celular', to_regclass('public.avisos_inscricoes') is not null and exists(select 1 from pg_proc where proname = 'avisos_do_dia'), 'Rodar o arquivo 025_avisos_no_celular.sql'),
 (3, 'SQL 026 · Alertas e Relatório Mensal', exists(select 1 from information_schema.columns where table_schema = 'public' and table_name = 'fazendas' and column_name = 'email_relatorio') and exists(select 1 from pg_proc where proname = 'alertas_consultor') and exists(select 1 from pg_proc where proname = 'resumo_mensal'), 'Rodar o arquivo 026_alertas_e_relatorio_mensal.sql'),
 (4, 'Extensão pg_cron (Agendamento)', exists(select 1 from pg_extension where extname = 'pg_cron'), 'Database › Extensions › ligar pg_cron'),
 (5, 'Extensão pg_net (Chamar a Função)', exists(select 1 from pg_extension where extname = 'pg_net'), 'Database › Extensions › ligar pg_net'),
 (6, 'Os 4 Agendamentos Farmplan', case when to_regclass('cron.job') is null then false else (xpath('/row/n/text()', query_to_xml($q$select count(*) as n from cron.job where jobname in ('farmplan-aviso-manha','farmplan-aviso-tarde','farmplan-alerta-consultor','farmplan-relatorio-mensal') and active$q$, false, true, '')))[1]::text = '4' end, 'Rodar o Passo B do arquivo de Segredos (SQL do cron)'),
 (7, 'Celulares com Aviso Ligado', case when to_regclass('public.avisos_inscricoes') is null then false else (xpath('/row/n/text()', query_to_xml('select count(*) as n from public.avisos_inscricoes', false, true, '')))[1]::text::int > 0 end, 'Abrir o app no celular e tocar em 🔔 Ligar'),
 (8, 'Fazenda com E-mail do Relatório', case when not exists(select 1 from information_schema.columns where table_schema = 'public' and table_name = 'fazendas' and column_name = 'email_relatorio') then false else (xpath('/row/n/text()', query_to_xml('select count(*) as n from public.fazendas where email_relatorio is not null', false, true, '')))[1]::text::int > 0 end, 'Cadastros › Geral › preencher os e-mails e Salvar Fazenda'),
 (9, 'SQL 027 · Relatório do Produtor', exists(select 1 from pg_proc where proname = 'resumo_mensal' and prosrc like '%destaques%'), 'Rodar o arquivo 027_relatorio_do_produtor.sql'),
 (10, 'SQL 028 · Relatório da Semana no WhatsApp', exists(select 1 from information_schema.columns where table_schema = 'public' and table_name = 'fazendas' and column_name = 'whatsapp_relatorio') and exists(select 1 from pg_proc where proname = 'resumo_semanal'), 'Rodar o arquivo 028_relatorio_semanal_whatsapp.sql'),
 (11, 'Agendamento do Relatório da Semana', case when to_regclass('cron.job') is null then false else (xpath('/row/n/text()', query_to_xml($q$select count(*) as n from cron.job where jobname = 'farmplan-relatorio-semanal' and active$q$, false, true, '')))[1]::text = '1' end, 'Rodar de novo o arquivo 028 (ele cria o agendamento de segunda às 7h)'),
 (12, 'SQL 029 · Site Atualiza Sozinho', exists(select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'baixas') and exists(select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'planejamento'), 'Rodar o arquivo 029_atualizacao_automatica.sql'),
 (13, 'SQL 030 · Cor da Semana Muda com a Baixa', exists(select 1 from pg_trigger where tgname = 'trg_status_pela_baixa' and not tgisinternal), 'Rodar o arquivo 030_status_pela_baixa.sql'),
 (14, 'Fazenda com WhatsApp do Relatório', case when not exists(select 1 from information_schema.columns where table_schema = 'public' and table_name = 'fazendas' and column_name = 'whatsapp_relatorio') then false else (xpath('/row/n/text()', query_to_xml('select count(*) as n from public.fazendas where coalesce(whatsapp_relatorio, '''') <> ''''', false, true, '')))[1]::text::int > 0 end, 'Cadastros › Geral › preencher o WhatsApp com DDD e Salvar Fazenda'),
 (15, 'SQL 031 · Andamento da Implantação', exists(select 1 from pg_proc where proname = 'avisos_ligados'), 'Rodar o arquivo 031_andamento_implantacao.sql')
)
select ordem as "Nº", item as "Item", case when ok then '✅ OK' else '❌ Falta' end as "Situação", case when ok then '' else se_faltar end as "O Que Fazer"
from c order by ordem;
